import hbs from 'handlebars';
import fs from 'fs/promises';

import { PipelineReport } from './index';
import { File } from '../../file';

import env from '../../../env';

/* Generated by @n1k1t/unit-generator */
it('should return null when compiling with no snapshots', async () => {
  const report = new PipelineReport({} as any);
  const result = await report.compile();
  expect(result).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should include the session id in the report location', () => {
  const report = new PipelineReport({ id: 'test-session-id', timestamp: Date.now() } as any);
  expect(report.location).toContain('test-session-id.html');
});

/* Generated by @n1k1t/unit-generator */
it('should place the report in the .pipelain/reports directory', () => {
  const report = new PipelineReport({ id: 'id', timestamp: Date.now() } as any);
  expect(report.location).toContain('.pipelain/reports');
});

/* Generated by @n1k1t/unit-generator */
it('should call fs.readFile for index.hbs during compilation', async () => {
  (env as any).dirs = { assets: 'test-assets' };
  const report = new PipelineReport({ meta: { usage: { llm: {} } } } as any);
  report.snapshots = [{ actions: [] }] as any;
  const spy = jest.spyOn(fs, 'readFile').mockResolvedValue('template');
  jest.spyOn(hbs, 'compile').mockReturnValue(() => 'html');
  await report.compile();
  expect(spy).toHaveBeenCalledWith(expect.stringContaining('index.hbs'), 'utf8');
});

/* Generated by @n1k1t/unit-generator */
it('should call fs.readFile for main.js during compilation', async () => {
  (env as any).dirs = { assets: 'test-assets' };
  const report = new PipelineReport({ meta: { usage: { llm: {} } } } as any);
  report.snapshots = [{ actions: [] }] as any;
  const spy = jest.spyOn(fs, 'readFile').mockResolvedValue('script');
  jest.spyOn(hbs, 'compile').mockReturnValue(() => 'html');
  await report.compile();
  expect(spy).toHaveBeenCalledWith(expect.stringContaining('main.js'), 'utf8');
});

/* Generated by @n1k1t/unit-generator */
it('should filter out empty reasoning actions during compilation', async () => {
  (env as any).dirs = { assets: 'test' };
  const report = new PipelineReport({ meta: { usage: { llm: {} } } } as any);
  const snapshot = {
    actions: [
      { type: 'ai:reasoning', output: '' },
      { type: 'text', output: 'content' },
    ],
  };
  report.snapshots = [snapshot] as any;
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  jest.spyOn(hbs, 'compile').mockReturnValue(() => '');
  await report.compile();
  expect(snapshot.actions).toHaveLength(1);
});

/* Generated by @n1k1t/unit-generator */
it('should return null when saving with no snapshots', async () => {
  const report = new PipelineReport({} as any);
  const result = await report.save();
  expect(result).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should call File.build with the correct location in save', async () => {
  (env as any).dirs = { assets: 'test' };
  const report = new PipelineReport({ meta: { usage: { llm: {} } } } as any);
  report.snapshots = [{ actions: [] }] as any;
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  jest.spyOn(hbs, 'compile').mockReturnValue(() => 'html');
  const buildSpy = jest.spyOn(File, 'build').mockResolvedValue({ write: jest.fn() } as any);
  await report.save('custom-path.html');
  expect(buildSpy).toHaveBeenCalledWith('custom-path.html');
});

/* Generated by @n1k1t/unit-generator */
it('should call file.write with compiled content in save', async () => {
  (env as any).dirs = { assets: 'test' };
  const report = new PipelineReport({ meta: { usage: { llm: {} } } } as any);
  report.snapshots = [{ actions: [] }] as any;
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  jest.spyOn(hbs, 'compile').mockReturnValue(() => 'compiled-html');
  const writeSpy = jest.fn();
  jest.spyOn(File, 'build').mockResolvedValue({ write: writeSpy } as any);
  await report.save();
  expect(writeSpy).toHaveBeenCalledWith('compiled-html');
});

/* Generated by @n1k1t/unit-generator */
it('should subscribe to step:ai:complete when building a report', () => {
  const session = { on: jest.fn() } as any;
  PipelineReport.build(session);
  expect(session.on).toHaveBeenCalledWith('step:ai:complete', expect.any(Function));
});

/* Generated by @n1k1t/unit-generator */
it('should subscribe to step:ai:error when building a report', () => {
  const session = { on: jest.fn() } as any;
  PipelineReport.build(session);
  expect(session.on).toHaveBeenCalledWith('step:ai:error', expect.any(Function));
});

/* Generated by @n1k1t/unit-generator */
it('should add a snapshot when step:ai:complete is emitted', () => {
  let listener: any;
  const session = {
    on: (event: string, cb: any) => {
      if (event === 'step:ai:complete') listener = cb;
    },
  } as any;
  const report = PipelineReport.build(session);
  listener({
    messages: [],
    actions: [{ toPlain: () => ({}) }],
    output: '',
    usage: {},
    step: { trace: () => [{ title: 'step' }] },
    llm: { name: 'n', model: 'm', limit: 1, reasoning: true, temperature: 0.5 },
  });
  expect(report.snapshots).toHaveLength(1);
});
