import { AttachmentContent } from './attachment';

/* Generated by @n1k1t/unit-generator */
it('should have location set to "system"', () => {
  const attachment = AttachmentContent.build({
    title: 'Test',
    content: 'data',
  });

  expect(attachment.location).toBe('system');
});

/* Generated by @n1k1t/unit-generator */
it('should render object content as a formatted JSON string', () => {
  const content = { foo: 'bar' };
  const attachment = AttachmentContent.build({
    title: 'Test',
    content,
  });

  expect(attachment.render()).toBe(JSON.stringify(content, null, 2));
});

/* Generated by @n1k1t/unit-generator */
it('should render array content as a formatted JSON string', () => {
  const content = [1, 2, 3];
  const attachment = AttachmentContent.build({
    title: 'Test',
    content,
  });

  expect(attachment.render()).toBe(JSON.stringify(content, null, 2));
});

/* Generated by @n1k1t/unit-generator */
it('should render string content as a string', () => {
  const attachment = AttachmentContent.build({
    title: 'Test',
    content: 'plain text',
  });

  expect(attachment.render()).toBe('plain text');
});

/* Generated by @n1k1t/unit-generator */
it('should render number content as a string', () => {
  const attachment = AttachmentContent.build({
    title: 'Test',
    content: 123,
  });

  expect(attachment.render()).toBe('123');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the instance with the same payload', () => {
  const payload = {
    title: 'Test',
    content: 'data',
    key: 'custom-key',
    extension: '.txt',
  };
  const attachment = AttachmentContent.build(payload);
  const cloned = attachment.clone();

  expect(cloned.payload).toEqual(attachment.payload);
});

/* Generated by @n1k1t/unit-generator */
it('should use the provided extension in the build method', () => {
  const attachment = AttachmentContent.build({
    title: 'Test',
    content: 'data',
    extension: '.csv',
  });

  expect(attachment.payload.extension).toBe('.csv');
});

/* Generated by @n1k1t/unit-generator */
it('should default extension to .json when content is an object', () => {
  const attachment = AttachmentContent.build({
    title: 'Test',
    content: { a: 1 },
  });

  expect(attachment.payload.extension).toBe('.json');
});

/* Generated by @n1k1t/unit-generator */
it('should have no extension when content is not an object and extension is not provided', () => {
  const attachment = AttachmentContent.build({
    title: 'Test',
    content: 'data',
  });

  expect(attachment.payload.extension).toBeUndefined();
});

/* Generated by @n1k1t/unit-generator */
it('should use the provided key in the build method', () => {
  const attachment = AttachmentContent.build({
    title: 'Test',
    content: 'data',
    key: 'manual-key',
  });

  expect(attachment.payload.key).toBe('manual-key');
});

/* Generated by @n1k1t/unit-generator */
it('should generate a kebab-case key from the title and extension', () => {
  const attachment = AttachmentContent.build({
    title: 'My Custom Title',
    content: {},
    extension: '.json',
  });

  expect(attachment.payload.key).toBe('my-custom-title.json');
});

/* Generated by @n1k1t/unit-generator */
it('should generate a kebab-case key from the title without extension if extension is missing', () => {
  const attachment = AttachmentContent.build({
    title: 'My Custom Title',
    content: 'data',
  });

  expect(attachment.payload.key).toBe('my-custom-title');
});
