import { Content, TContentLocation } from './model';
import { GroupContent } from './group';

/* Generated by @n1k1t/unit-generator */
it('should create a GroupContent instance using build', () => {
  expect(GroupContent.build([])).toBeInstanceOf(GroupContent);
});

/* Generated by @n1k1t/unit-generator */
it('should render empty payload as empty string', () => {
  expect(GroupContent.build([]).render()).toBe('');
});

/* Generated by @n1k1t/unit-generator */
it('should render multiple contents joined by double newline', () => {
  const c1 = { render: () => 'a' } as Content;
  const c2 = { render: () => 'b' } as Content;
  expect(GroupContent.build([c1, c2]).render()).toBe('a\n\nb');
});

/* Generated by @n1k1t/unit-generator */
it('should return empty array for empty payload when flattening', () => {
  expect(GroupContent.build([]).flat()).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should return non-group contents as is when flattening', () => {
  const c1 = {} as Content;
  expect(GroupContent.build([c1]).flat()).toEqual([c1]);
});

/* Generated by @n1k1t/unit-generator */
it('should flatten nested GroupContent', () => {
  const c1 = {} as Content;
  const nested = GroupContent.build([c1]);
  expect(GroupContent.build([nested]).flat()).toEqual([c1]);
});

/* Generated by @n1k1t/unit-generator */
it('should flatten deeply nested GroupContent', () => {
  const c1 = {} as Content;
  const nested2 = GroupContent.build([c1]);
  const nested1 = GroupContent.build([nested2]);
  expect(GroupContent.build([nested1]).flat()).toEqual([c1]);
});

/* Generated by @n1k1t/unit-generator */
it('should return this instance after relocate', () => {
  const group = GroupContent.build([]);
  expect(group.relocate({} as TContentLocation)).toBe(group);
});

/* Generated by @n1k1t/unit-generator */
it('should call relocate on all children with the provided location', () => {
  const relocate = jest.fn();
  const child = { relocate } as unknown as Content;
  const location = {} as TContentLocation;
  GroupContent.build([child]).relocate(location);
  expect(relocate).toHaveBeenCalledWith(location);
});

/* Generated by @n1k1t/unit-generator */
it('should create a new instance when cloning', () => {
  const group = GroupContent.build([]);
  expect(group.clone()).not.toBe(group);
});

/* Generated by @n1k1t/unit-generator */
it('should have the same payload after cloning', () => {
  const payload = [] as Content[];
  expect(GroupContent.build(payload).clone().payload).toBe(payload);
});
