import { Content } from './model';

/* Generated by @n1k1t/unit-generator */
it('should set the type property from constructor', () => {
  class MockContent extends Content<'plain', string> {
    render() {
      return '';
    }
    clone() {
      return new MockContent(this.type, this.payload);
    }
  }
  const content = new MockContent('plain', 'test');
  expect(content.type).toBe('plain');
});

/* Generated by @n1k1t/unit-generator */
it('should set the payload property from constructor', () => {
  class MockContent extends Content<'plain', string> {
    render() {
      return '';
    }
    clone() {
      return new MockContent(this.type, this.payload);
    }
  }
  const content = new MockContent('plain', 'test');
  expect(content.payload).toBe('test');
});

/* Generated by @n1k1t/unit-generator */
it('should have undefined location by default', () => {
  class MockContent extends Content<'plain', string> {
    render() {
      return '';
    }
    clone() {
      return new MockContent(this.type, this.payload);
    }
  }
  const content = new MockContent('plain', 'test');
  expect(content.location).toBeUndefined();
});

/* Generated by @n1k1t/unit-generator */
it('should call clone method when relocate is called', () => {
  class MockContent extends Content<'plain', string> {
    public cloneCalled = false;
    render() {
      return '';
    }
    clone() {
      this.cloneCalled = true;
      return new MockContent(this.type, this.payload);
    }
  }
  const content = new MockContent('plain', 'test');
  content.relocate('system');
  expect(content.cloneCalled).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should set the location on the cloned instance when relocate is called', () => {
  class MockContent extends Content<'plain', string> {
    render() {
      return '';
    }
    clone() {
      return new MockContent(this.type, this.payload);
    }
  }
  const content = new MockContent('plain', 'test');
  const relocated = content.relocate('system');
  expect(relocated.location).toBe('system');
});

/* Generated by @n1k1t/unit-generator */
it('should not modify the original instance location when relocate is called', () => {
  class MockContent extends Content<'plain', string> {
    render() {
      return '';
    }
    clone() {
      return new MockContent(this.type, this.payload);
    }
  }
  const content = new MockContent('plain', 'test');
  content.relocate('system');
  expect(content.location).toBeUndefined();
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance when relocate is called', () => {
  class MockContent extends Content<'plain', string> {
    render() {
      return '';
    }
    clone() {
      return new MockContent(this.type, this.payload);
    }
  }
  const content = new MockContent('plain', 'test');
  const relocated = content.relocate('user');
  expect(relocated).not.toBe(content);
});

/* Generated by @n1k1t/unit-generator */
it('should return an instance of the same class when relocate is called', () => {
  class MockContent extends Content<'plain', string> {
    render() {
      return '';
    }
    clone() {
      return new MockContent(this.type, this.payload);
    }
  }
  const content = new MockContent('plain', 'test');
  const relocated = content.relocate('system');
  expect(relocated).toBeInstanceOf(MockContent);
});
