import { PlainContent } from './plain';

/* Generated by @n1k1t/unit-generator */
it('should create an instance with "plain" type using build', () => {
  const content = PlainContent.build('test');
  expect(content.type).toBe('plain');
});

/* Generated by @n1k1t/unit-generator */
it('should set the payload correctly using build', () => {
  const content = PlainContent.build('test');
  expect(content.payload).toBe('test');
});

/* Generated by @n1k1t/unit-generator */
it('should have default location set to "system"', () => {
  const content = PlainContent.build('test');
  expect(content.location).toBe('system');
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance when cloned', () => {
  const original = PlainContent.build('test');
  const cloned = original.clone();
  expect(cloned).not.toBe(original);
});

/* Generated by @n1k1t/unit-generator */
it('should have the same payload in the cloned instance', () => {
  const original = PlainContent.build('test');
  const cloned = original.clone();
  expect(cloned.payload).toBe('test');
});

/* Generated by @n1k1t/unit-generator */
it('should render the payload without changes if no indentation is present', () => {
  const content = PlainContent.build('hello');
  expect(content.render()).toBe('hello');
});

/* Generated by @n1k1t/unit-generator */
it('should remove leading indentation from a single line', () => {
  const content = PlainContent.build('  hello');
  expect(content.render()).toBe('hello');
});

/* Generated by @n1k1t/unit-generator */
it('should remove common indentation from multiple lines', () => {
  const content = PlainContent.build('  line1\n  line2');
  expect(content.render()).toBe('line1\nline2');
});

/* Generated by @n1k1t/unit-generator */
it('should handle leading newline and remove indentation from subsequent lines', () => {
  const content = PlainContent.build('\n  hello');
  expect(content.render()).toBe('\nhello');
});

/* Generated by @n1k1t/unit-generator */
it('should return empty string when rendering an empty payload', () => {
  const content = PlainContent.build('');
  expect(content.render()).toBe('');
});

/* Generated by @n1k1t/unit-generator */
it('should return the same whitespace string when rendering a payload with only spaces', () => {
  const content = PlainContent.build('   ');
  expect(content.render()).toBe('   ');
});

/* Generated by @n1k1t/unit-generator */
it('should update location when relocate is called', () => {
  const content = PlainContent.build('test');
  const relocated = content.relocate('user');
  expect(relocated.location).toBe('user');
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance when relocate is called', () => {
  const instance = PlainContent.build('test');
  const relocated = instance.relocate('user');
  expect(relocated).not.toBe(instance);
});

/* Generated by @n1k1t/unit-generator */
it('should slice all lines by the offset of the first non-whitespace character', () => {
  const content = PlainContent.build('  line1\nline2');
  expect(content.render()).toBe('line1\nne2');
});

/* Generated by @n1k1t/unit-generator */
it('should handle cases where the first non-whitespace character is after a newline and spaces', () => {
  const content = PlainContent.build('  \n  a');
  expect(content.render()).toBe('\n');
});
