import { RulesContent } from './rules';

/* Generated by @n1k1t/unit-generator */
it('should create an instance of RulesContent using build', () => {
  const rules = RulesContent.build(['rule 1']);
  expect(rules).toBeInstanceOf(RulesContent);
});

/* Generated by @n1k1t/unit-generator */
it('should set the payload correctly when built', () => {
  const rules = RulesContent.build(['rule 1', 'rule 2']);
  expect(rules.payload).toEqual(['rule 1', 'rule 2']);
});

/* Generated by @n1k1t/unit-generator */
it('should have the location property set to system', () => {
  const rules = RulesContent.build([]);
  expect(rules.location).toBe('system');
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance when clone is called', () => {
  const rules = RulesContent.build(['rule 1']);
  const cloned = rules.clone();
  expect(cloned).not.toBe(rules);
});

/* Generated by @n1k1t/unit-generator */
it('should have the same payload in the cloned instance', () => {
  const rules = RulesContent.build(['rule 1']);
  const cloned = rules.clone();
  expect(cloned.payload).toEqual(['rule 1']);
});

/* Generated by @n1k1t/unit-generator */
it('should return an instance of RulesContent when cloned', () => {
  const rules = RulesContent.build(['rule 1']);
  const cloned = rules.clone();
  expect(cloned).toBeInstanceOf(RulesContent);
});
