import json2md from 'json2md';
import { SourcesContent } from './sources';

/* Generated by @n1k1t/unit-generator */
it('should have the location property set to system', () => {
  const content = SourcesContent.build([]);
  expect(content.location).toBe('system');
});

/* Generated by @n1k1t/unit-generator */
it('should serialize payload with path only correctly', () => {
  const content = SourcesContent.build([{ path: 'src/index.ts' }]);
  expect(content.serialize()).toEqual(['`src/index.ts`']);
});

/* Generated by @n1k1t/unit-generator */
it('should serialize payload with path and title correctly', () => {
  const content = SourcesContent.build([{ path: 'src/index.ts', title: 'Main File' }]);
  expect(content.serialize()).toEqual(['`src/index.ts`: Main File']);
});

/* Generated by @n1k1t/unit-generator */
it('should render the content as a markdown ordered list', () => {
  const content = SourcesContent.build([{ path: 'file.ts' }]);
  const expected = json2md({ ol: ['`file.ts`'] });
  expect(content.render()).toBe(expected);
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance when clone is called', () => {
  const content = SourcesContent.build([{ path: 'file.ts' }]);
  const cloned = content.clone();
  expect(cloned).not.toBe(content);
});

/* Generated by @n1k1t/unit-generator */
it('should return an instance of SourcesContent when clone is called', () => {
  const content = SourcesContent.build([{ path: 'file.ts' }]);
  const cloned = content.clone();
  expect(cloned).toBeInstanceOf(SourcesContent);
});

/* Generated by @n1k1t/unit-generator */
it('should preserve the payload when clone is called', () => {
  const payload = [{ path: 'file.ts', title: 'Title' }];
  const content = SourcesContent.build(payload);
  const cloned = content.clone();
  expect(cloned.serialize()).toEqual(content.serialize());
});

/* Generated by @n1k1t/unit-generator */
it('should correctly handle multiple items in serialize', () => {
  const content = SourcesContent.build([{ path: 'a.ts' }, { path: 'b.ts', title: 'B' }]);
  expect(content.serialize()).toEqual(['`a.ts`', '`b.ts`: B']);
});
