import json2md from 'json2md';
import { TasksContent } from './tasks';

/* Generated by @n1k1t/unit-generator */
it('should have the correct location', () => {
  const tasks = TasksContent.build(['task 1']);
  expect(tasks.location).toBe('user');
});

/* Generated by @n1k1t/unit-generator */
it('should render the payload as an ordered list in markdown', () => {
  const payload = ['task 1', 'task 2'];
  const tasks = TasksContent.build(payload);
  expect(tasks.render()).toBe(json2md({ ol: payload }));
});

/* Generated by @n1k1t/unit-generator */
it('should clone the instance with the same payload', () => {
  const payload = ['task 1'];
  const tasks = TasksContent.build(payload);
  const cloned = tasks.clone();
  expect(cloned.payload).toEqual(tasks.payload);
});

/* Generated by @n1k1t/unit-generator */
it('should create a new instance when cloning', () => {
  const tasks = TasksContent.build(['task 1']);
  const cloned = tasks.clone();
  expect(cloned).not.toBe(tasks);
});

/* Generated by @n1k1t/unit-generator */
it('should be an instance of TasksContent when built', () => {
  const tasks = TasksContent.build(['task 1']);
  expect(tasks).toBeInstanceOf(TasksContent);
});
