import { PipelineStdout } from './model';

/* Generated by @n1k1t/unit-generator */
it('should create an instance using build static method', () => {
  expect(PipelineStdout.build()).toBeInstanceOf(PipelineStdout);
});

/* Generated by @n1k1t/unit-generator */
it('should use console as default logger when build is called without arguments', () => {
  const stdout = PipelineStdout.build();
  expect((stdout as any).logger).toBe(console);
});

/* Generated by @n1k1t/unit-generator */
it('should use provided logger when build is called with a logger', () => {
  const logger = { info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  expect((stdout as any).logger).toBe(logger);
});

/* Generated by @n1k1t/unit-generator */
it('should register all hooks on session when listen is called', () => {
  const session = { on: jest.fn() } as any;
  const stdout = PipelineStdout.build();
  stdout.listen(session);
  expect(session.on).toHaveBeenCalledTimes(7);
});

/* Generated by @n1k1t/unit-generator */
it('should return this from listen method', () => {
  const session = { on: jest.fn() } as any;
  const stdout = PipelineStdout.build();
  expect(stdout.listen(session)).toBe(stdout);
});

/* Generated by @n1k1t/unit-generator */
it('should allow overriding a hook handler', () => {
  const session = { on: jest.fn() } as any;
  const stdout = PipelineStdout.build();
  const handler = jest.fn();
  stdout.override('warning', handler);
  stdout.listen(session);
  const registeredHandler = session.on.mock.calls.find((c: any) => c[0] === 'warning')[1];
  registeredHandler({ message: 'test' });
  expect(handler).toHaveBeenCalledWith({ message: 'test' });
});

/* Generated by @n1k1t/unit-generator */
it('should return this from override method', () => {
  const stdout = PipelineStdout.build();
  expect(stdout.override('warning', () => {})).toBe(stdout);
});

/* Generated by @n1k1t/unit-generator */
it('should log warning message using logger info in default warning hook', () => {
  const logger = { info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'warning')[1];
  handler({ message: 'warn-msg' });
  expect(logger.info).toHaveBeenCalledWith('warn-msg');
});

/* Generated by @n1k1t/unit-generator */
it('should log message with trace in default log hook', () => {
  const logger = { info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'log')[1];
  handler({ pipeline: { trace: () => [{ title: 'Child' }, { title: 'Parent' }] }, message: ['msg1', 'msg2'] });
  expect(logger.info).toHaveBeenCalledWith('Parent - Child:', 'msg1', 'msg2');
});

/* Generated by @n1k1t/unit-generator */
it('should log run event when state is not INIT', () => {
  const logger = { info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'run')[1];
  handler({ pipeline: { trace: () => [{ title: 'P' }] }, meta: { state: 'DONE', spent: 100 } });
  expect(logger.info).toHaveBeenCalledWith('P: [DONE]', 'in 100ms');
});

/* Generated by @n1k1t/unit-generator */
it('should not log run event when state is INIT', () => {
  const logger = { info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'run')[1];
  handler({ pipeline: { trace: () => [{ title: 'P' }] }, meta: { state: 'INIT', spent: 0 } });
  expect(logger.info).not.toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should log step:run event when state is not INIT', () => {
  const logger = { info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'step:run')[1];
  handler({ step: { trace: () => [{ title: 'S' }] }, meta: { state: 'DONE', spent: 50 } });
  expect(logger.info).toHaveBeenCalledWith('S: [DONE]', 'in 50ms');
});

/* Generated by @n1k1t/unit-generator */
it('should log step:llm:tool event when state is not INIT', () => {
  const logger = { info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'step:ai:tool')[1];
  handler({
    step: { trace: () => [{ title: 'S' }] },
    name: 'T',
    meta: { state: 'DONE', spent: 30 },
    preview: () => 'tool-msg',
  });
  expect(logger.info).toHaveBeenCalledWith('S:', 'Tool [T] [DONE] in 30ms', '\ntool-msg');
});

/* Generated by @n1k1t/unit-generator */
it('should log step:llm:reasoning event when state is not INIT', () => {
  const logger = { info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'step:ai:reasoning')[1];
  handler({
    step: { trace: () => [{ title: 'S' }] },
    meta: { state: 'DONE', spent: 40 },
    preview: () => 'reason-msg',
  });
  expect(logger.info).toHaveBeenCalledWith('S:', 'Reasoning [DONE] in 40ms', '\nreason-msg');
});
