import { PipelineStdout } from './model';
import { Meta } from '../../meta';

const buildMeta = (state: Meta['state'], spent: number): Meta => Object.assign(Meta.build(), { state, spent });

/* Generated by @n1k1t/unit-generator */
it('should create an instance using build static method', () => {
  expect(PipelineStdout.build()).toBeInstanceOf(PipelineStdout);
});

/* Generated by @n1k1t/unit-generator */
it('should use console as default logger when build is called without arguments', () => {
  const stdout = PipelineStdout.build();
  expect((stdout as any).logger).toBe(console);
});

/* Generated by @n1k1t/unit-generator */
it('should use provided logger when build is called with a logger', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  expect((stdout as any).logger).toBe(logger);
});

/* Generated by @n1k1t/unit-generator */
it('should register all hooks on session when listen is called', () => {
  const session = { on: jest.fn() } as any;
  const stdout = PipelineStdout.build();
  stdout.listen(session);
  expect(session.on).toHaveBeenCalledTimes(8);
});

/* Generated by @n1k1t/unit-generator */
it('should return this from listen method', () => {
  const session = { on: jest.fn() } as any;
  const stdout = PipelineStdout.build();
  expect(stdout.listen(session)).toBe(stdout);
});

/* Generated by @n1k1t/unit-generator */
it('should allow overriding a hook handler', () => {
  const session = { on: jest.fn() } as any;
  const stdout = PipelineStdout.build();
  const handler = jest.fn();
  stdout.override('log', handler);
  stdout.listen(session);
  const registeredHandler = session.on.mock.calls.find((c: any) => c[0] === 'log')[1];
  registeredHandler({ message: ['test'] });
  expect(handler).toHaveBeenCalledWith({ message: ['test'] });
});

/* Generated by @n1k1t/unit-generator */
it('should return this from override method', () => {
  const stdout = PipelineStdout.build();
  expect(stdout.override('log', () => {})).toBe(stdout);
});

/* Generated by @n1k1t/unit-generator */
it('should log DEBUG message using logger debug in default log hook', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'log')[1];
  handler({ level: 'DEBUG', pipeline: { trace: () => [{ title: 'P' }] }, message: ['msg'] });
  expect(logger.debug).toHaveBeenCalledWith('P:', 'msg');
});

/* Generated by @n1k1t/unit-generator */
it('should log INFO message using logger info in default log hook', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'log')[1];
  handler({ level: 'INFO', pipeline: { trace: () => [{ title: 'P' }] }, message: ['msg'] });
  expect(logger.info).toHaveBeenCalledWith('P:', 'msg');
});

/* Generated by @n1k1t/unit-generator */
it('should log WARN message using logger warn in default log hook', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'log')[1];
  handler({ level: 'WARN', pipeline: { trace: () => [{ title: 'P' }] }, message: ['msg'] });
  expect(logger.warn).toHaveBeenCalledWith('P:', 'msg');
});

/* Generated by @n1k1t/unit-generator */
it('should log message with trace in default log hook', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'log')[1];
  handler({ level: 'INFO', pipeline: { trace: () => [{ title: 'Child' }, { title: 'Parent' }] }, message: ['msg1', 'msg2'] });
  expect(logger.info).toHaveBeenCalledWith('Parent - Child:', 'msg1', 'msg2');
});

/* Generated by @n1k1t/unit-generator */
it('should log run event when state is not INIT', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'run')[1];
  handler({ pipeline: { trace: () => [{ title: 'P' }], meta: buildMeta('DONE', 100) } });
  expect(logger.info).toHaveBeenCalledWith('P: [DONE]', 'in 100ms');
});

/* Generated by @n1k1t/unit-generator */
it('should not log run event when state is INIT', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'run')[1];
  handler({ pipeline: { trace: () => [{ title: 'P' }], meta: buildMeta('INIT', 0) } });
  expect(logger.info).not.toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should log step:run event when state is not INIT', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'step:run')[1];
  handler({ step: { trace: () => [{ title: 'S' }], meta: buildMeta('DONE', 50) } });
  expect(logger.info).toHaveBeenCalledWith('S: [DONE]', 'in 50ms');
});

/* Generated by @n1k1t/unit-generator */
it('should log step:llm:tool event when state is not INIT', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'step:ai:tool')[1];
  handler({
    step: { trace: () => [{ title: 'S' }] },
    name: 'T',
    meta: buildMeta('DONE', 30),
    preview: () => 'tool-msg',
  });
  expect(logger.info).toHaveBeenCalledWith('S:', 'Tool [T] [DONE] in 30ms', '\ntool-msg');
});

/* Generated by @n1k1t/unit-generator */
it('should log step:llm:reasoning event when state is not INIT', () => {
  const logger = { debug: jest.fn(), info: jest.fn(), warn: jest.fn() };
  const stdout = PipelineStdout.build(logger);
  const session = { on: jest.fn() } as any;
  stdout.listen(session);
  const handler = session.on.mock.calls.find((c: any) => c[0] === 'step:ai:reasoning')[1];
  handler({
    step: { trace: () => [{ title: 'S' }] },
    meta: buildMeta('DONE', 40),
    output: 'reasoning',
    preview: () => 'reason-msg',
  });
  expect(logger.info).toHaveBeenCalledWith('S:', 'Reasoning [DONE] in 40ms', '\nreason-msg');
});
