import { PipelineContext } from './context';

/* Generated by @n1k1t/unit-generator */
it('should create an instance using build static method', () => {
  const project = {} as any;
  const context = PipelineContext.build(project);
  expect(context).toBeInstanceOf(PipelineContext);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize project property from constructor', () => {
  const project = { id: 'test-project' } as any;
  const context = new PipelineContext(project);
  expect(context.project).toBe(project);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize state as an empty object by default', () => {
  const context = new PipelineContext({} as any);
  expect(context.state).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('should initialize input as undefined by default', () => {
  const context = new PipelineContext({} as any);
  expect(context.input).toBeUndefined();
});

/* Generated by @n1k1t/unit-generator */
it('should assign input via assign method', () => {
  const context = new PipelineContext({} as any);
  const input = { data: 123 };
  context.assign({ input });
  expect(context.input).toBe(input);
});

/* Generated by @n1k1t/unit-generator */
it('should assign state via assign method', () => {
  const context = new PipelineContext({} as any);
  const state = { key: 'value' };
  context.assign({ state });
  expect(context.state).toBe(state);
});

/* Generated by @n1k1t/unit-generator */
it('should assign llm via assign method', () => {
  const context = new PipelineContext({} as any);
  const llm = { id: 'test-llm' } as any;
  context.assign({ llm });
  expect(context.llm).toBe(llm);
});

/* Generated by @n1k1t/unit-generator */
it('should return the same instance from assign method', () => {
  const context = new PipelineContext({} as any);
  const result = context.assign({});
  expect(result).toBe(context);
});

/* Generated by @n1k1t/unit-generator */
it('should merge state with provided payload', () => {
  const context = new PipelineContext({} as any);
  context.state = { a: 1 };
  context.merge({ state: { b: 2 } });
  expect(context.state).toEqual({ a: 1, b: 2 });
});

/* Generated by @n1k1t/unit-generator */
it('should overwrite arrays in state when merging', () => {
  const context = new PipelineContext({} as any);
  context.state = { items: [1, 2] };
  context.merge({ state: { items: [3] } });
  expect(context.state.items).toEqual([3]);
});

/* Generated by @n1k1t/unit-generator */
it('should merge input when it is an object', () => {
  const context = new PipelineContext({} as any);
  context.input = { a: 1 };
  context.merge({ input: { b: 2 } });
  expect(context.input).toEqual({ a: 1, b: 2 });
});

/* Generated by @n1k1t/unit-generator */
it('should overwrite arrays in input when merging', () => {
  const context = new PipelineContext({} as any);
  context.input = { items: [1, 2] };
  context.merge({ input: { items: [3] } });
  expect(context.input.items).toEqual([3]);
});

/* Generated by @n1k1t/unit-generator */
it('should not change input during merge if current input is not an object', () => {
  const context = new PipelineContext({} as any);
  context.input = 'not-an-object';
  context.merge({ input: { a: 1 } as any });
  expect(context.input).toBe('not-an-object');
});

/* Generated by @n1k1t/unit-generator */
it('should call llm.assign when merging llm', () => {
  const context = new PipelineContext({} as any);
  const mockLlm = { assign: jest.fn().mockReturnValue({ assigned: true }) };
  context.llm = mockLlm as any;
  context.merge({ llm: { temperature: 0.7 } });
  expect(mockLlm.assign).toHaveBeenCalledWith({ temperature: 0.7 });
});

/* Generated by @n1k1t/unit-generator */
it('should update llm property with the result of llm.assign', () => {
  const context = new PipelineContext({} as any);
  const newLlm = { assigned: true };
  const mockLlm = { assign: jest.fn().mockReturnValue(newLlm) };
  context.llm = mockLlm as any;
  context.merge({ llm: { temperature: 0.7 } });
  expect(context.llm).toBe(newLlm);
});

/* Generated by @n1k1t/unit-generator */
it('should return the same instance from merge method', () => {
  const context = new PipelineContext({} as any);
  const result = context.merge({});
  expect(result).toBe(context);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize input from defaults in constructor', () => {
  const project = {} as any;
  const defaults = { input: { x: 1 } };
  const context = new PipelineContext(project, defaults);
  expect(context.input).toEqual({ x: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('should initialize state from defaults in constructor', () => {
  const project = {} as any;
  const defaults = { state: { y: 2 } };
  const context = new PipelineContext(project, defaults);
  expect(context.state).toEqual({ y: 2 });
});
