import { PipelineContext } from './context';
import { LlmRouter } from '../llm';
import { Project } from '../project';

/* Generated by @n1k1t/unit-generator */
it('assign() should update input, state and llm when provided', () => {
  const project = new Project({ sources: { skills: {} as any } } as any);
  const context = PipelineContext.build<any>(project, { input: { a: 1 }, state: { x: 1 } });

  const llm = LlmRouter.build().provide();
  const next = context.assign({
    input: { a: 2 },
    state: { x: 2 },
    llm,
  });

  expect(next.input).toEqual({ a: 2 });
  expect(next.state).toEqual({ x: 2 });
  expect(next.llm).toBe(llm);
});

/* Generated by @n1k1t/unit-generator */
it('merge() should merge input objects using deep merge with array replacement', () => {
  const project = new Project({ sources: { skills: {} as any } } as any);
  const context = PipelineContext.build<any>(project, { input: { a: { b: 1 }, arr: [1, 2] } });

  context.merge({ input: { a: { c: 2 }, arr: [3] } });

  expect(context.input).toEqual({ a: { b: 1, c: 2 }, arr: [3] });
});

/* Generated by @n1k1t/unit-generator */
it('merge() should merge state objects deeply', () => {
  const project = new Project({ sources: { skills: {} as any } } as any);
  const context = PipelineContext.build<any>(project, { state: { s: { a: 1 }, n: 1 } });

  context.merge({ state: { s: { b: 2 } } });

  expect(context.state).toEqual({ s: { a: 1, b: 2 }, n: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('merge() should assign llm using provider assign() semantics', () => {
  const project = new Project({ sources: { skills: {} as any } } as any);
  const context = PipelineContext.build<any>(project);

  const oldLlm = context.llm;
  const temperature = 0.42;
  context.merge({ llm: { temperature } });

  expect(context.llm).not.toBe(oldLlm);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineContext.build() should create an instance with given project and defaults', () => {
  const project = new Project({ sources: { skills: {} as any } } as any);
  const context = PipelineContext.build<any>(project, {
    input: { hello: 'world' },
    state: { count: 1 },
  });

  expect(context.project).toBe(project);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineContext.build() should apply defaults to input and state', () => {
  const project = new Project({ sources: { skills: {} as any } } as any);
  const context = PipelineContext.build<any>(project, {
    input: { hello: 'world' },
    state: { count: 1 },
  });

  expect(context.state).toEqual({ count: 1 });
});
