import { PipelineParameters } from './parameters';
import { PipelineFactory } from './factory';
import { ContentFactory } from '../content';
import { Bash } from '../bash';

/* Generated by @n1k1t/unit-generator */
it('should create an instance of PipelineParameters using the static build method', () => {
  const pipeline = { context: { project: { cwd: '' } }, session: {} } as any;
  expect(PipelineParameters.build(pipeline)).toBeInstanceOf(PipelineParameters);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize the context property from the provided pipeline', () => {
  const context = { project: { cwd: '' } } as any;
  const pipeline = { context, session: {} } as any;
  expect(new PipelineParameters(pipeline).context).toBe(context);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize the session property from the provided pipeline', () => {
  const session = {} as any;
  const pipeline = { context: { project: { cwd: '' } }, session } as any;
  expect(new PipelineParameters(pipeline).session).toBe(session);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize the factory property by calling PipelineFactory.build', () => {
  const pipeline = { context: { project: { cwd: '' } }, session: {} } as any;
  const spy = jest.spyOn(PipelineFactory, 'build');
  new PipelineParameters(pipeline);
  expect(spy).toHaveBeenCalledWith(pipeline);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize utils.content by calling ContentFactory.build with the project from context', () => {
  const project = { cwd: '' };
  const pipeline = { context: { project }, session: {} } as any;
  const spy = jest.spyOn(ContentFactory, 'build');
  new PipelineParameters(pipeline);
  expect(spy).toHaveBeenCalledWith(project);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize utils.bash by calling Bash.build with the project cwd', () => {
  const project = { cwd: '/test/path' };
  const pipeline = { context: { project }, session: {} } as any;
  const spy = jest.spyOn(Bash, 'build');
  new PipelineParameters(pipeline);
  expect(spy).toHaveBeenCalledWith({ cwd: '/test/path' });
});

/* Generated by @n1k1t/unit-generator */
it('should emit a log event with the correct payload when utils.log is called', () => {
  const session = { emit: jest.fn() };
  const pipeline = { context: { project: { cwd: '' } }, session } as any;
  const params = new PipelineParameters(pipeline);
  params.utils.log('test message');
  expect(session.emit).toHaveBeenCalledWith('log', { message: ['test message'], pipeline });
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance that is not the same as the original when extend is called', () => {
  const pipeline = { context: { project: { cwd: '' } }, session: {} } as any;
  const params = new PipelineParameters(pipeline);
  expect(params.extend({})).not.toBe(params);
});

/* Generated by @n1k1t/unit-generator */
it('should merge the provided payload into the new instance when extend is called', () => {
  const pipeline = { context: { project: { cwd: '' } }, session: {} } as any;
  const params = new PipelineParameters(pipeline);
  const extended = params.extend({ customProp: 'value' });
  expect(extended.customProp).toBe('value');
});
