import EventEmitter from 'events';
import { PipelineSession } from './session';

/* Generated by @n1k1t/unit-generator */
it('should create an instance of PipelineSession via build', () => {
  const session = PipelineSession.build();
  expect(session).toBeInstanceOf(PipelineSession);
});

/* Generated by @n1k1t/unit-generator */
it('should have an id property of type string', () => {
  const session = new PipelineSession();
  expect(typeof session.id).toBe('string');
});

/* Generated by @n1k1t/unit-generator */
it('should have meta.llm.tokens.input initialized to 0', () => {
  const session = new PipelineSession();
  expect(session.meta.llm.tokens.input).toBe(0);
});

/* Generated by @n1k1t/unit-generator */
it('should have meta.llm.tokens.output initialized to 0', () => {
  const session = new PipelineSession();
  expect(session.meta.llm.tokens.output).toBe(0);
});

/* Generated by @n1k1t/unit-generator */
it('should inherit from EventEmitter', () => {
  const session = new PipelineSession();
  expect(session).toBeInstanceOf(EventEmitter);
});
