import { PipelineAiFallbackAction } from './fallback';

/* Generated by @n1k1t/unit-generator */
it('should return null when provide is called', () => {
  const action = new PipelineAiFallbackAction({} as any, { old: {} as any, new: {} as any }, {} as any);
  expect(action.provide()).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should return "ai:fallback" as type in toPlain', () => {
  const action = new PipelineAiFallbackAction({} as any, { old: {} as any, new: {} as any }, {} as any);
  expect(action.toPlain().type).toBe('ai:fallback');
});

/* Generated by @n1k1t/unit-generator */
it('should include the error in toPlain', () => {
  const error = { message: 'test error' } as any;
  const action = new PipelineAiFallbackAction({} as any, { old: {} as any, new: {} as any }, error);
  expect(action.toPlain().error).toEqual(error);
});

/* Generated by @n1k1t/unit-generator */
it('should include the old llm name in toPlain', () => {
  const llm = { old: { name: 'old-provider' } as any, new: {} as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.old.name).toBe('old-provider');
});

/* Generated by @n1k1t/unit-generator */
it('should include the old llm model in toPlain', () => {
  const llm = { old: { model: 'old-model' } as any, new: {} as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.old.model).toBe('old-model');
});

/* Generated by @n1k1t/unit-generator */
it('should include the old llm options in toPlain', () => {
  const options = { custom: true };
  const llm = { old: { options } as any, new: {} as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.old.options).toEqual(options);
});

/* Generated by @n1k1t/unit-generator */
it('should include the old llm temperature in toPlain parameters', () => {
  const llm = { old: { temperature: 0.5 } as any, new: {} as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.old.parameters.temperature).toBe(0.5);
});

/* Generated by @n1k1t/unit-generator */
it('should include the old llm reasoning in toPlain parameters', () => {
  const llm = { old: { reasoning: 'high' } as any, new: {} as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.old.parameters.reasoning).toBe('high');
});

/* Generated by @n1k1t/unit-generator */
it('should include the new llm name in toPlain', () => {
  const llm = { old: {} as any, new: { name: 'new-provider' } as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.new.name).toBe('new-provider');
});

/* Generated by @n1k1t/unit-generator */
it('should include the new llm model in toPlain', () => {
  const llm = { old: {} as any, new: { model: 'new-model' } as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.new.model).toBe('new-model');
});

/* Generated by @n1k1t/unit-generator */
it('should include the new llm options in toPlain', () => {
  const options = { custom: false };
  const llm = { old: {} as any, new: { options } as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.new.options).toEqual(options);
});

/* Generated by @n1k1t/unit-generator */
it('should include the new llm temperature in toPlain parameters', () => {
  const llm = { old: {} as any, new: { temperature: 0.8 } as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.new.parameters.temperature).toBe(0.8);
});

/* Generated by @n1k1t/unit-generator */
it('should include the new llm reasoning in toPlain parameters', () => {
  const llm = { old: {} as any, new: { reasoning: 'low' } as any };
  const action = new PipelineAiFallbackAction({} as any, llm, {} as any);
  expect(action.toPlain().llm.new.parameters.reasoning).toBe('low');
});

/* Generated by @n1k1t/unit-generator */
it('should initialize output as an empty string', () => {
  const action = new PipelineAiFallbackAction({} as any, { old: {} as any, new: {} as any }, {} as any);
  expect(action.output).toBe('');
});

/* Generated by @n1k1t/unit-generator */
it('should initialize delta as an empty string', () => {
  const action = new PipelineAiFallbackAction({} as any, { old: {} as any, new: {} as any }, {} as any);
  expect(action.delta).toBe('');
});

/* Generated by @n1k1t/unit-generator */
it('should create an instance of PipelineAiFallbackAction via build', () => {
  const action = PipelineAiFallbackAction.build({} as any, {} as any, { old: {} as any, new: {} as any });
  expect(action).toBeInstanceOf(PipelineAiFallbackAction);
});
