import { PipelineAiAction } from './model';
import { Meta } from '../../../../meta';

/* Generated by @n1k1t/unit-generator */
it('should initialize timestamp with a number', () => {
  class TestAction extends PipelineAiAction {
    public provide() {
      return null;
    }
    public toPlain() {
      return {};
    }
  }
  const action = new TestAction({} as any);
  expect(typeof action.timestamp).toBe('number');
});

/* Generated by @n1k1t/unit-generator */
it('should initialize meta with state INIT', () => {
  class TestAction extends PipelineAiAction {
    public provide() {
      return null;
    }
    public toPlain() {
      return {};
    }
  }
  const action = new TestAction({} as any);
  expect(action.meta.state).toBe('INIT');
});

/* Generated by @n1k1t/unit-generator */
it('should initialize meta with spent 0', () => {
  class TestAction extends PipelineAiAction {
    public provide() {
      return null;
    }
    public toPlain() {
      return {};
    }
  }
  const action = new TestAction({} as any);
  expect(action.meta.spent).toBe(0);
});

/* Generated by @n1k1t/unit-generator */
it('should assign step to the property', () => {
  class TestAction extends PipelineAiAction {
    public provide() {
      return null;
    }
    public toPlain() {
      return {};
    }
  }
  const step = {} as any;
  const action = new TestAction(step);
  expect(action.step).toBe(step);
});

/* Generated by @n1k1t/unit-generator */
it('should update meta state when meta.actualize is called', () => {
  class TestAction extends PipelineAiAction {
    public provide() {
      return null;
    }
    public toPlain() {
      return {};
    }
  }
  const action = new TestAction({} as any);
  action.meta.actualize('DONE');
  expect(action.meta.state).toBe('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('should update meta spent when meta.actualize is called', () => {
  class TestAction extends PipelineAiAction {
    public provide() {
      return null;
    }
    public toPlain() {
      return {};
    }
  }
  const action = new TestAction({} as any);
  action.meta.actualize('DONE');
  expect(action.meta.spent).toBeGreaterThanOrEqual(0);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize meta with INIT state', () => {
  class TestAction extends PipelineAiAction {
    public provide() {
      return null;
    }
    public toPlain() {
      return {};
    }
  }
  const action = new TestAction({} as any);
  expect(action.meta).toBeInstanceOf(Meta);
  expect(action.meta.state).toBe('INIT');
});
