import { PipelineAiReasoningAction } from './reasoning';

/* Generated by @n1k1t/unit-generator */
it('should initialize id from the start fragment', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'test-id', type: 'reasoning-start' } as any);
  expect(action.id).toBe('test-id');
});

/* Generated by @n1k1t/unit-generator */
it('should initialize trace.initial from fragment providerMetadata', () => {
  const action = new PipelineAiReasoningAction(
    {} as any,
    {} as any,
    { id: 'id', type: 'reasoning-start', providerMetadata: { foo: 'bar' } } as any,
  );
  expect(action.trace.initial).toEqual({ foo: 'bar' });
});

/* Generated by @n1k1t/unit-generator */
it('should initialize output as an empty string', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  expect(action.output).toBe('');
});

/* Generated by @n1k1t/unit-generator */
it('should append text to output on enrich', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.actualize = jest.fn().mockReturnValue(action);
  action.enrich({ text: 'hello ' } as any);
  action.enrich({ text: 'world' } as any);
  expect(action.output).toBe('hello world');
});

/* Generated by @n1k1t/unit-generator */
it('should update delta on enrich', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.actualize = jest.fn().mockReturnValue(action);
  action.enrich({ text: 'first' } as any);
  action.enrich({ text: 'second' } as any);
  expect(action.delta).toBe('second');
});

/* Generated by @n1k1t/unit-generator */
it('should update trace.final on enrich if providerMetadata is present', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.actualize = jest.fn().mockReturnValue(action);
  action.enrich({ text: '', providerMetadata: { step: 1 } } as any);
  expect(action.trace.final).toEqual({ step: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('should call actualize with PENDING on enrich', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.actualize = jest.fn().mockReturnValue(action);
  action.enrich({ text: '' } as any);
  expect(action.actualize).toHaveBeenCalledWith('PENDING');
});

/* Generated by @n1k1t/unit-generator */
it('should trim output on complete', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.actualize = jest.fn().mockReturnValue(action);
  action.output = '  content  ';
  action.complete({ type: 'reasoning-end' } as any);
  expect(action.output).toBe('content');
});

/* Generated by @n1k1t/unit-generator */
it('should update trace.final on complete if providerMetadata is present', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.actualize = jest.fn().mockReturnValue(action);
  action.complete({ type: 'reasoning-end', providerMetadata: { done: true } } as any);
  expect(action.trace.final).toEqual({ done: true });
});

/* Generated by @n1k1t/unit-generator */
it('should call actualize with DONE on complete', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.actualize = jest.fn().mockReturnValue(action);
  action.complete({ type: 'reasoning-end' } as any);
  expect(action.actualize).toHaveBeenCalledWith('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('should return initial trace via provide("initial")', () => {
  const action = new PipelineAiReasoningAction(
    {} as any,
    {} as any,
    { id: 'id', type: 'reasoning-start', providerMetadata: { init: 1 } } as any,
  );
  expect(action.provide('initial')).toEqual({ init: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('should return final trace via provide("final") if available', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.trace.final = { final: 2 };
  expect(action.provide('final')).toEqual({ final: 2 });
});

/* Generated by @n1k1t/unit-generator */
it('should return initial trace via provide("final") if final is not available', () => {
  const action = new PipelineAiReasoningAction(
    {} as any,
    {} as any,
    { id: 'id', type: 'reasoning-start', providerMetadata: { init: 1 } } as any,
  );
  expect(action.provide('final')).toEqual({ init: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('should return null from provide if no metadata is available', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  expect(action.provide('initial')).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should format reasoning content with output and trace', () => {
  const action = new PipelineAiReasoningAction(
    {} as any,
    {} as any,
    { id: 'id', type: 'reasoning-start', providerMetadata: { m: 1 } } as any,
  );
  action.output = 'reasoning text';
  expect(action.format()).toEqual({ type: 'reasoning', text: 'reasoning text', providerOptions: { m: 1 } });
});

/* Generated by @n1k1t/unit-generator */
it('should return correct type in toPlain', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  expect(action.toPlain().type).toBe('ai:reasoning');
});

/* Generated by @n1k1t/unit-generator */
it('should include llm name and model in toPlain', () => {
  const llm = { name: 'test-llm', model: 'test-model', options: {}, temperature: 0, reasoning: false };
  const action = new PipelineAiReasoningAction({} as any, llm as any, { id: 'id', type: 'reasoning-start' } as any);
  expect(action.toPlain().llm.name).toBe('test-llm');
});

/* Generated by @n1k1t/unit-generator */
it('should include llm parameters in toPlain', () => {
  const llm = { name: 'n', model: 'm', options: {}, temperature: 0.7, reasoning: 'high' };
  const action = new PipelineAiReasoningAction({} as any, llm as any, { id: 'id', type: 'reasoning-start' } as any);
  expect(action.toPlain().llm.parameters).toEqual({ temperature: 0.7, reasoning: 'high' });
});

/* Generated by @n1k1t/unit-generator */
it('should replace newlines with ↩ in preview', () => {
  const action = new PipelineAiReasoningAction({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  action.output = 'line1\nline2';
  expect(action.preview()).toBe('line1↩ line2');
});

/* Generated by @n1k1t/unit-generator */
it('should create instance via static build method', () => {
  const action = PipelineAiReasoningAction.build({} as any, {} as any, { id: 'id', type: 'reasoning-start' } as any);
  expect(action).toBeInstanceOf(PipelineAiReasoningAction);
});
