import { PipelineAiToolAction, PipelineAiToolActionError } from './tool';

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolActionError.convert should create a text error from an Error object', () => {
  const error = new Error('test error');
  const result = PipelineAiToolActionError.convert(error);
  expect(result.type).toBe('text');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolActionError.convert should create a json error from a plain object', () => {
  const error = { foo: 'bar' };
  const result = PipelineAiToolActionError.convert(error);
  expect(result.payload).toEqual({ foo: 'bar' });
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolActionError.convert should create a json error from a valid JSON string', () => {
  const jsonStr = '{"error":"bad request"}';
  const result = PipelineAiToolActionError.convert(jsonStr);
  expect(result.type).toBe('json');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolActionError.convert should return a text error for numeric input', () => {
  const result = PipelineAiToolActionError.convert(500);
  expect(result.payload).toBe('500');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolActionError.is should return true for matching type', () => {
  const error = new PipelineAiToolActionError('json', { a: 1 });
  expect(error.is('json')).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolActionError constructor should stringify object payload for the error message', () => {
  const error = new PipelineAiToolActionError('json', { foo: 'bar' });
  expect(error.message).toBe('{"foo":"bar"}');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction should initialize input as json when fragment input is an object', () => {
  const fragment = { toolCallId: '1', toolName: 't', input: { x: 1 } };
  const action = new PipelineAiToolAction({} as any, {} as any, fragment as any);
  expect(action.input.type).toBe('json');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.preview should replace newlines with return symbol followed by a space for text input', () => {
  const action = new PipelineAiToolAction(
    {} as any,
    {} as any,
    { toolCallId: '1', toolName: 't', input: 'a\nb' } as any,
  );
  expect(action.preview()).toBe('a↩ b');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.provide should return initial provider metadata when kind is initial', () => {
  const fragment = { toolCallId: '1', toolName: 't', input: {}, providerMetadata: { p: 1 } };
  const action = new PipelineAiToolAction({} as any, {} as any, fragment as any);
  expect(action.provide('initial')).toEqual({ p: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.provide should return trace.final if it exists when kind is final', () => {
  const action = new PipelineAiToolAction(
    {} as any,
    {} as any,
    { toolCallId: '1', toolName: 't', input: {}, providerMetadata: { init: 1 } } as any,
  );
  action.trace.final = { final: 2 };
  expect(action.provide('final')).toEqual({ final: 2 });
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.format("call-part") should return ToolCallPart with correct toolCallId', () => {
  const action = new PipelineAiToolAction(
    {} as any,
    {} as any,
    { toolCallId: 'id-123', toolName: 't', input: {} } as any,
  );
  expect(action.format('call-part').toolCallId).toBe('id-123');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.complete should update trace.final with provider metadata from fragment', () => {
  const action = new PipelineAiToolAction(
    {} as any,
    {} as any,
    { toolCallId: 'id', toolName: 'name', input: {} } as any,
  );
  action.actualize = jest.fn().mockReturnValue(action);
  action.complete('DONE', {
    type: 'tool-result',
    toolCallId: 'id',
    toolName: 'name',
    providerMetadata: { final: true },
  } as any);
  expect(action.trace.final).toEqual({ final: true });
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.complete should set output to json when state is DONE and output is an object', () => {
  const action = new PipelineAiToolAction(
    {} as any,
    {} as any,
    { toolCallId: 'id', toolName: 'name', input: {} } as any,
  );
  action.actualize = jest.fn().mockReturnValue(action);
  action.complete('DONE', {
    type: 'tool-result',
    toolCallId: 'id',
    toolName: 'name',
    output: { success: true },
  } as any);
  expect(action.output?.type).toBe('json');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.complete should set output to error when state is ERROR', () => {
  const action = new PipelineAiToolAction(
    {} as any,
    {} as any,
    { toolCallId: 'id', toolName: 'name', input: {} } as any,
  );
  action.actualize = jest.fn().mockReturnValue(action);
  action.complete('ERROR', { type: 'tool-error', toolCallId: 'id', toolName: 'name', error: 'fail' } as any);
  expect(action.output?.type).toBe('error');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.format("result-part") should return "Empty" text output when no output is set', () => {
  const action = new PipelineAiToolAction(
    {} as any,
    {} as any,
    { toolCallId: 'id', toolName: 'name', input: {} } as any,
  );
  const result = action.format('result-part');
  expect((result.output as any).value).toBe('Empty');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.format("result-part") should return error-json type when the error is a json error', () => {
  const action = new PipelineAiToolAction({} as any, {} as any, { toolCallId: '1', toolName: 't', input: {} } as any);
  action.output = { type: 'error', value: new PipelineAiToolActionError('json', { code: 1 }) };
  const result = action.format('result-part');
  expect(result.output.type).toBe('error-json');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.toPlain should include llm model name', () => {
  const llm = { name: 'n', model: 'test-model', temperature: 0, reasoning: 'r' };
  const action = new PipelineAiToolAction({} as any, llm as any, { toolCallId: '1', toolName: 't', input: {} } as any);
  expect(action.toPlain().llm.model).toBe('test-model');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineAiToolAction.build should return a new instance of PipelineAiToolAction', () => {
  const action = PipelineAiToolAction.build({} as any, {} as any, { toolCallId: '1', toolName: 't', input: {} } as any);
  expect(action).toBeInstanceOf(PipelineAiToolAction);
});
