import { buildCounter, cast, wait, chunkify, buildTimeSpendMarker, preview, disposify } from './common';

/* Generated by @n1k1t/unit-generator */
it('buildCounter should increment by default step', () => {
  const counter = buildCounter(10, 5);
  expect(counter()).toBe(15);
});

/* Generated by @n1k1t/unit-generator */
it('buildCounter should increment by custom value when called', () => {
  const counter = buildCounter(10, 5);
  expect(counter(2)).toBe(12);
});

/* Generated by @n1k1t/unit-generator */
it('buildCounter should maintain state between calls', () => {
  const counter = buildCounter(0, 1);
  counter();
  expect(counter()).toBe(2);
});

/* Generated by @n1k1t/unit-generator */
it('cast should return the same value provided', () => {
  const obj = { a: 1 };
  expect(cast(obj)).toBe(obj);
});

/* Generated by @n1k1t/unit-generator */
it('wait should return a promise with a value property', () => {
  const promise = wait(50);
  expect(promise.value).toBe(50);
});

/* Generated by @n1k1t/unit-generator */
it('wait should resolve after the specified time', async () => {
  const start = Date.now();
  await wait(50);
  expect(Date.now() - start).toBeGreaterThanOrEqual(45);
});

/* Generated by @n1k1t/unit-generator */
it('chunkify should process all items in the list', async () => {
  const results = await chunkify([1, 2, 3], 2, async (x) => x);
  expect(results.length).toBe(3);
});

/* Generated by @n1k1t/unit-generator */
it('chunkify should return results with correct indices', async () => {
  const results = await chunkify(['a', 'b'], 1, async (x) => x);
  expect(results[1].index).toBe(1);
});

/* Generated by @n1k1t/unit-generator */
it('chunkify should capture fulfilled results', async () => {
  const results = await chunkify([10], 1, async (x) => x * 2);
  expect(results[0].result).toEqual({ status: 'fulfilled', value: 20 });
});

/* Generated by @n1k1t/unit-generator */
it('chunkify should capture rejected results', async () => {
  const results = await chunkify([10], 1, async () => {
    throw new Error('fail');
  });
  expect(results[0].result.status).toBe('rejected');
});

/* Generated by @n1k1t/unit-generator */
it('buildTimeSpendMarker should return the difference from the initial timestamp', () => {
  const marker = buildTimeSpendMarker(1000);
  expect(marker(1500)).toBe(500);
});

/* Generated by @n1k1t/unit-generator */
it('buildTimeSpendMarker should update the last timestamp after a call', () => {
  const marker = buildTimeSpendMarker(1000);
  marker(1500);
  expect(marker(1600)).toBe(100);
});

/* Generated by @n1k1t/unit-generator */
it('preview should format string values with double quotes', () => {
  expect(preview({ name: 'test' })).toBe('name="test"');
});

/* Generated by @n1k1t/unit-generator */
it('preview should format numeric values without quotes', () => {
  expect(preview({ age: 25 })).toBe('age=25');
});

/* Generated by @n1k1t/unit-generator */
it('preview should format arrays as item counts', () => {
  expect(preview({ list: [1, 2, 3] })).toBe('list=[3 items]');
});

/* Generated by @n1k1t/unit-generator */
it('preview should format nested objects as placeholders', () => {
  expect(preview({ data: { id: 1 } })).toBe('data={...}');
});

/* Generated by @n1k1t/unit-generator */
it('preview should truncate the output based on the limit', () => {
  expect(preview({ long: '1234567890' }, 8)).toBe('long="12...');
});

/* Generated by @n1k1t/unit-generator */
it('disposify should return an object containing the original entity', () => {
  const entity = { id: 1 };
  const disposable = disposify({ entity, exit: async () => {} });
  expect(disposable.entity).toBe(entity);
});

/* Generated by @n1k1t/unit-generator */
it('disposify should call the exit function when disposed', async () => {
  const exit = jest.fn();
  const disposable = disposify({ entity: 'test', exit });
  await disposable[Symbol.asyncDispose]();
  expect(exit).toHaveBeenCalledWith('test');
});
