import { buildMetaManager } from './meta';

/* Generated by @n1k1t/unit-generator */
it('should return INIT state when init is called', () => {
  const manager = buildMetaManager();
  expect(manager.init().state).toEqual('INIT');
});

/* Generated by @n1k1t/unit-generator */
it('should return 0 spent time when init is called', () => {
  const manager = buildMetaManager();
  expect(manager.init().spent).toEqual(0);
});

/* Generated by @n1k1t/unit-generator */
it('should return DONE state when done is called', () => {
  const manager = buildMetaManager();
  expect(manager.done().state).toEqual('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('should return ERROR state when error is called', () => {
  const manager = buildMetaManager();
  expect(manager.error().state).toEqual('ERROR');
});

/* Generated by @n1k1t/unit-generator */
it('should return PENDING state when pending is called', () => {
  const manager = buildMetaManager();
  expect(manager.pending().state).toEqual('PENDING');
});

/* Generated by @n1k1t/unit-generator */
it('should return spent time from marker when done is called', () => {
  const spy = jest.spyOn(Date, 'now').mockReturnValueOnce(1000).mockReturnValueOnce(1500);
  const manager = buildMetaManager();
  const result = manager.done().spent;
  spy.mockRestore();
  expect(result).toEqual(500);
});

/* Generated by @n1k1t/unit-generator */
it('should return spent time from marker when error is called', () => {
  const spy = jest.spyOn(Date, 'now').mockReturnValueOnce(1000).mockReturnValueOnce(1500);
  const manager = buildMetaManager();
  const result = manager.error().spent;
  spy.mockRestore();
  expect(result).toEqual(500);
});

/* Generated by @n1k1t/unit-generator */
it('should return spent time from marker when pending is called', () => {
  const spy = jest.spyOn(Date, 'now').mockReturnValueOnce(1000).mockReturnValueOnce(1500);
  const manager = buildMetaManager();
  const result = manager.pending().spent;
  spy.mockRestore();
  expect(result).toEqual(500);
});

/* Generated by @n1k1t/unit-generator */
it('should track spent time sequentially between calls', () => {
  const spy = jest.spyOn(Date, 'now').mockReturnValueOnce(1000).mockReturnValueOnce(1200).mockReturnValueOnce(1500);
  const manager = buildMetaManager();
  manager.pending();
  const result = manager.done().spent;
  spy.mockRestore();
  expect(result).toEqual(300);
});

/* Generated by @n1k1t/unit-generator */
it('should not call marker when init is called', () => {
  const spy = jest.spyOn(Date, 'now').mockReturnValueOnce(1000).mockReturnValueOnce(1500);
  const manager = buildMetaManager();
  manager.init();
  const result = manager.done().spent;
  spy.mockRestore();
  expect(result).toEqual(500);
});
