import { LlmAnthropicProvider } from './anthropic';

/* Generated by @n1k1t/unit-generator */
it('should have name "anthropic"', () => {
  const provider = LlmAnthropicProvider.build('model', { connection: { key: 'key' } });
  expect(provider.name).toBe('anthropic');
});

/* Generated by @n1k1t/unit-generator */
it('should set the model property during build', () => {
  const provider = LlmAnthropicProvider.build('my-model', { connection: { key: 'key' } });
  expect(provider.model).toBe('my-model');
});

/* Generated by @n1k1t/unit-generator */
it('should set the connection property during build', () => {
  const connection = { key: 'key', url: 'url' };
  const provider = LlmAnthropicProvider.build('model', { connection });
  expect(provider.connection).toEqual(connection);
});

/* Generated by @n1k1t/unit-generator */
it('should set the temperature property during build', () => {
  const provider = LlmAnthropicProvider.build('model', { connection: { key: 'key' }, temperature: 0.5 });
  expect(provider.temperature).toBe(0.5);
});

/* Generated by @n1k1t/unit-generator */
it('should set the reasoning property during build', () => {
  const provider = LlmAnthropicProvider.build('model', { connection: { key: 'key' }, reasoning: 'low' });
  expect(provider.reasoning).toBe('low');
});

/* Generated by @n1k1t/unit-generator */
it('should set the limit property during build', () => {
  const provider = LlmAnthropicProvider.build('model', { connection: { key: 'key' }, limit: 10 });
  expect(provider.limit).toBe(10);
});

/* Generated by @n1k1t/unit-generator */
it('should set the options property during build', () => {
  const options = <any>{ some: 'option' };
  const provider = LlmAnthropicProvider.build('model', { connection: { key: 'key' }, options });
  expect(provider.options).toEqual(options);
});

/* Generated by @n1k1t/unit-generator */
it('should use empty options if not provided in build', () => {
  const provider = LlmAnthropicProvider.build('model', { connection: { key: 'key' } } as any);
  expect(provider.options).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same model', () => {
  const provider = LlmAnthropicProvider.build('m1', { connection: { key: 'k' } });
  const clone = provider.clone();
  expect(clone.model).toBe('m1');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same temperature', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, temperature: 0.8 });
  const clone = provider.clone();
  expect(clone.temperature).toBe(0.8);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same reasoning', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, reasoning: 'high' });
  const clone = provider.clone();
  expect(clone.reasoning).toBe('high');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same limit', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, limit: 42 });
  const clone = provider.clone();
  expect(clone.limit).toBe(42);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a new options object', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, options: <any>{ a: 1 } });
  const clone = provider.clone();
  expect(clone.options).not.toBe(provider.options);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same options values', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, options: <any>{ a: 1 } });
  const clone = provider.clone();
  expect(clone.options).toEqual({ a: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a new tools object', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, tools: { t: {} as any } });
  const clone = provider.clone();
  expect(clone.tools).not.toBe(provider.tools);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same tools values', () => {
  const tools = { t: {} as any };
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, tools });
  const clone = provider.clone();
  expect(clone.tools).toEqual(tools);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a new skills array', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, skills: [{} as any] });
  const clone = provider.clone();
  expect(clone.skills).not.toBe(provider.skills);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same skills values', () => {
  const skills = [{} as any];
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, skills });
  const clone = provider.clone();
  expect(clone.skills).toEqual(skills);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a new mcp array', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, mcp: [{} as any] });
  const clone = provider.clone();
  expect(clone.mcp).not.toBe(provider.mcp);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same mcp values', () => {
  const mcp = [{} as any];
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, mcp });
  const clone = provider.clone();
  expect(clone.mcp).toEqual(mcp);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a new fallback object', () => {
  const provider = LlmAnthropicProvider.build('m', {
    connection: { key: 'k' },
    fallback: { strategy: 'restart', providers: [] },
  });
  const clone = provider.clone();
  expect(clone.fallback).not.toBe(provider.fallback);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same fallback strategy', () => {
  const provider = LlmAnthropicProvider.build('m', {
    connection: { key: 'k' },
    fallback: { strategy: 'continue', providers: [] },
  });
  const clone = provider.clone();
  expect(clone.fallback?.strategy).toBe('continue');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a new fallback providers array', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, fallback: { providers: [{} as any] } });
  const clone = provider.clone();
  expect(clone.fallback?.providers).not.toBe(provider.fallback?.providers);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same fallback providers', () => {
  const providers = [{} as any];
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' }, fallback: { providers } });
  const clone = provider.clone();
  expect(clone.fallback?.providers).toEqual(providers);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider without fallback if it is not defined', () => {
  const provider = LlmAnthropicProvider.build('m', { connection: { key: 'k' } });
  const clone = provider.clone();
  expect(clone.fallback).toBeUndefined();
});
