import { LlmGoogleProvider } from './google';

/* Generated by @n1k1t/unit-generator */
it('should have name "google"', () => {
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'test-key' } });
  expect(provider.name).toBe('google');
});

/* Generated by @n1k1t/unit-generator */
it('should set default thinkingConfig in build if options are not provided', () => {
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'test-key' } });
  expect(provider.options).toEqual({ thinkingConfig: { includeThoughts: true } });
});

/* Generated by @n1k1t/unit-generator */
it('should use provided options in build', () => {
  const options = { thinkingConfig: { includeThoughts: false } };
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'test-key' }, options });
  expect(provider.options).toEqual(options);
});

/* Generated by @n1k1t/unit-generator */
it('should use empty options if provided in build', () => {
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, options: {} as any });
  expect(provider.options).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance when clone is called', () => {
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'test-key' } });
  const clone = provider.clone();
  expect(clone).not.toBe(provider);
});

/* Generated by @n1k1t/unit-generator */
it('should copy model name when clone is called', () => {
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'test-key' } });
  const clone = provider.clone();
  expect(clone.model).toBe('gemini-pro');
});

/* Generated by @n1k1t/unit-generator */
it('should copy connection when clone is called', () => {
  const connection = { key: 'test-key', url: 'test-url' };
  const provider = LlmGoogleProvider.build('gemini-pro', { connection });
  const clone = provider.clone();
  expect(clone.connection).toEqual(connection);
});

/* Generated by @n1k1t/unit-generator */
it('should copy temperature when clone is called', () => {
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, temperature: 0.7 });
  const clone = provider.clone();
  expect(clone.temperature).toBe(0.7);
});

/* Generated by @n1k1t/unit-generator */
it('should copy limit when clone is called', () => {
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, limit: 50 });
  const clone = provider.clone();
  expect(clone.limit).toBe(50);
});

/* Generated by @n1k1t/unit-generator */
it('should copy reasoning when clone is called', () => {
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, reasoning: 'high' });
  const clone = provider.clone();
  expect(clone.reasoning).toBe('high');
});

/* Generated by @n1k1t/unit-generator */
it('should copy skills to a new array when clone is called', () => {
  const skills = [{ name: 'skill1' }] as any;
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, skills });
  const clone = provider.clone();
  expect(clone.skills).not.toBe(provider.skills);
});

/* Generated by @n1k1t/unit-generator */
it('should copy tools to a new object when clone is called', () => {
  const tools = { tool1: {} } as any;
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, tools });
  const clone = provider.clone();
  expect(clone.tools).not.toBe(provider.tools);
});

/* Generated by @n1k1t/unit-generator */
it('should copy mcp to a new array when clone is called', () => {
  const mcp = [{}] as any;
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, mcp });
  const clone = provider.clone();
  expect(clone.mcp).not.toBe(provider.mcp);
});

/* Generated by @n1k1t/unit-generator */
it('should copy fallback when clone is called', () => {
  const fallback = { strategy: 'continue' as const, providers: [] };
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, fallback });
  const clone = provider.clone();
  expect(clone.fallback).toEqual(fallback);
});

/* Generated by @n1k1t/unit-generator */
it('should copy fallback strategy when clone is called', () => {
  const fallback = { strategy: 'continue' as const, providers: [] };
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, fallback });
  const clone = provider.clone();
  expect(clone.fallback?.strategy).toBe('continue');
});

/* Generated by @n1k1t/unit-generator */
it('should copy fallback providers to a new array when clone is called', () => {
  const fallback = { strategy: 'continue' as const, providers: [] };
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, fallback });
  const clone = provider.clone();
  expect(clone.fallback?.providers).not.toBe(provider.fallback?.providers);
});

/* Generated by @n1k1t/unit-generator */
it('should copy options to a new object when clone is called', () => {
  const options = { thinkingConfig: { includeThoughts: true } };
  const provider = LlmGoogleProvider.build('gemini-pro', { connection: { key: 'k' }, options });
  const clone = provider.clone();
  expect(clone.options).not.toBe(provider.options);
});
