import { LlmMistralProvider } from './mistral';

/* Generated by @n1k1t/unit-generator */
it('should have the name set to mistral', () => {
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'low',
    limit: 100,
    skills: [],
    mcp: [],
  });
  expect(provider.name).toBe('mistral');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same model', () => {
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'low',
    limit: 100,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.model).toBe('model-id');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same temperature', () => {
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.5,
    reasoning: 'low',
    limit: 100,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.temperature).toBe(0.5);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same connection', () => {
  const connection = { key: 'key', url: 'url' };
  const provider = LlmMistralProvider.build('model-id', {
    connection,
    temperature: 0.7,
    reasoning: 'low',
    limit: 100,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.connection).toEqual(connection);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same reasoning setting', () => {
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'low',
    limit: 100,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.reasoning).toBe('low');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same limit', () => {
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'low',
    limit: 500,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.limit).toBe(500);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a copy of skills array', () => {
  const skills = <any>['skill1'];
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'low',
    limit: 100,
    skills,
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.skills).not.toBe(skills);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a copy of mcp array', () => {
  const mcp = <any>['mcp1'];
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'low',
    limit: 100,
    skills: [],
    mcp,
  });
  const cloned = provider.clone();
  expect(cloned.mcp).not.toBe(mcp);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a copy of options object', () => {
  const options = { safePrompt: true };
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'low',
    limit: 100,
    skills: [],
    mcp: [],
    options,
  });
  const cloned = provider.clone();
  expect(cloned.options).not.toBe(options);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize options to an empty object in build if not provided', () => {
  const provider = LlmMistralProvider.build('model-id', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: false,
    limit: 100,
    skills: [],
    mcp: [],
  } as any);
  expect(provider.options).toEqual({});
});
