import { LlmProvider } from './model';

/* Generated by @n1k1t/unit-generator */
it('should initialize limit with default value 30', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  expect(provider.limit).toBe(30);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize limit from provided value', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {}, limit: 50 });
  expect(provider.limit).toBe(50);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize connection', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const connection = { key: 'key', url: 'url' };
  const provider = new MockLlmProvider('model', { connection, options: {} });
  expect(provider.connection).toEqual(connection);
});

/* Generated by @n1k1t/unit-generator */
it('should cast to another provider type', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  expect(provider.cast(MockLlmProvider as any)).toBe(provider);
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance when calling assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  const assigned = provider.assign({});
  expect(assigned).not.toBe(provider);
});

/* Generated by @n1k1t/unit-generator */
it('should update temperature via assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  const assigned = provider.assign({ temperature: 0.5 });
  expect(assigned.temperature).toBe(0.5);
});

/* Generated by @n1k1t/unit-generator */
it('should update options via assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: { a: 1 } });
  const assigned = provider.assign({ options: { a: 2 } });
  expect(assigned.options).toEqual({ a: 2 });
});

/* Generated by @n1k1t/unit-generator */
it('should update fallback via assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  const fallback = { providers: [] };
  const assigned = provider.assign({ fallback });
  expect(assigned.fallback).toBe(fallback);
});

/* Generated by @n1k1t/unit-generator */
it('should update tools via assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  const tools = { tool1: {} as any };
  const assigned = provider.assign({ tools });
  expect(assigned.tools).toBe(tools);
});

/* Generated by @n1k1t/unit-generator */
it('should update skills via assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  const skills = [{} as any];
  const assigned = provider.assign({ skills });
  expect(assigned.skills).toBe(skills);
});

/* Generated by @n1k1t/unit-generator */
it('should update mcp via assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  const mcp = [{} as any];
  const assigned = provider.assign({ mcp });
  expect(assigned.mcp).toBe(mcp);
});

/* Generated by @n1k1t/unit-generator */
it('should update limit via assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  const assigned = provider.assign({ limit: 10 });
  expect(assigned.limit).toBe(10);
});

/* Generated by @n1k1t/unit-generator */
it('should update reasoning via assign', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  const assigned = provider.assign({ reasoning: 'high' });
  expect(assigned.reasoning).toBe('high');
});

/* Generated by @n1k1t/unit-generator */
it('should return null from next if no fallback providers', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const provider = new MockLlmProvider('model', { connection: { key: 'key' }, options: {} });
  expect(provider.next()).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should return first provider from next', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const p2 = new MockLlmProvider('m2', { connection: { key: 'k2' }, options: {} });
  const p1 = new MockLlmProvider('m1', { connection: { key: 'k1' }, options: {}, fallback: { providers: [p2] } });
  expect(p1.next()?.provider.model).toBe('m2');
});

/* Generated by @n1k1t/unit-generator */
it('should use restart strategy by default in next', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const p2 = new MockLlmProvider('m2', { connection: { key: 'k2' }, options: {} });
  const p1 = new MockLlmProvider('m1', { connection: { key: 'k1' }, options: {}, fallback: { providers: [p2] } });
  expect(p1.next()?.strategy).toBe('restart');
});

/* Generated by @n1k1t/unit-generator */
it('should propagate remaining fallbacks in next', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const p2 = new MockLlmProvider('m2', { connection: { key: 'k2' }, options: {} });
  const p3 = new MockLlmProvider('m3', { connection: { key: 'k3' }, options: {} });
  const p1 = new MockLlmProvider('m1', { connection: { key: 'k1' }, options: {}, fallback: { providers: [p2, p3] } });
  expect(p1.next()?.provider.fallback?.providers).toEqual([p3]);
});

/* Generated by @n1k1t/unit-generator */
it('should use provided strategy in next', () => {
  class MockLlmProvider extends LlmProvider {
    public name = 'mock';
    public tag = {} as any;
    public clone(): this {
      return new MockLlmProvider(this.model, this.provided) as this;
    }
  }
  const p2 = new MockLlmProvider('m2', { connection: { key: 'k2' }, options: {} });
  const p1 = new MockLlmProvider('m1', {
    connection: { key: 'k1' },
    options: {},
    fallback: { strategy: 'continue', providers: [p2] },
  });
  expect(p1.next()?.strategy).toBe('continue');
});
