import { LlmOpenaiProvider } from './openai';

/* Generated by @n1k1t/unit-generator */
it('should have name "openai"', () => {
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'test-key' } });
  expect(provider.name).toBe('openai');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider and return a new instance', () => {
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' } });
  const clone = provider.clone();
  expect(clone).not.toBe(provider);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same model name', () => {
  const provider = LlmOpenaiProvider.build('gpt-4-clone', { connection: { key: 'k' } });
  const clone = provider.clone();
  expect(clone.model).toBe('gpt-4-clone');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same temperature', () => {
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, temperature: 0.123 });
  const clone = provider.clone();
  expect(clone.temperature).toBe(0.123);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same reasoning', () => {
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, reasoning: 'medium' });
  const clone = provider.clone();
  expect(clone.reasoning).toBe('medium');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same limit', () => {
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, limit: 100 });
  const clone = provider.clone();
  expect(clone.limit).toBe(100);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a copy of options', () => {
  const options = <any>{ custom: 'option' };
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, options });
  const clone = provider.clone();
  expect(clone.options).not.toBe(provider.options);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a copy of tools', () => {
  const tools = { myTool: {} as any };
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, tools });
  const clone = provider.clone();
  expect(clone.tools).not.toBe(provider.tools);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a copy of skills', () => {
  const skills = [{ name: 'skill' } as any];
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, skills });
  const clone = provider.clone();
  expect(clone.skills).not.toBe(provider.skills);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a copy of mcp', () => {
  const mcp = [{ name: 'mcp' } as any];
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, mcp });
  const clone = provider.clone();
  expect(clone.mcp).not.toBe(provider.mcp);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a new fallback object', () => {
  const fallback = { strategy: 'restart' as const, providers: [] };
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, fallback });
  const clone = provider.clone();
  expect(clone.fallback).not.toBe(provider.fallback);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a copy of fallback providers array', () => {
  const fallback = { strategy: 'restart' as const, providers: [] };
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, fallback });
  const clone = provider.clone();
  expect(clone.fallback?.providers).not.toBe(provider.fallback?.providers);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same fallback strategy', () => {
  const fallback = { strategy: 'continue' as const, providers: [] };
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' }, fallback });
  const clone = provider.clone();
  expect(clone.fallback?.strategy).toBe('continue');
});

/* Generated by @n1k1t/unit-generator */
it('static build should initialize options to empty object if not provided', () => {
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' } } as any);
  expect(provider.options).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('should have default limit of 30 if not provided', () => {
  const provider = LlmOpenaiProvider.build('gpt-4', { connection: { key: 'k' } });
  expect(provider.limit).toBe(30);
});
