import { LlmProxyProvider } from './proxy';

/* Generated by @n1k1t/unit-generator */
it('should create an instance of LlmProxyProvider using build', () => {
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  expect(provider).toBeInstanceOf(LlmProxyProvider);
});

/* Generated by @n1k1t/unit-generator */
it('should have name set to proxy', () => {
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  expect(provider.name).toBe('proxy');
});

/* Generated by @n1k1t/unit-generator */
it('should call createOpenAI when model name contains gpt', () => {
  const openai = require('@ai-sdk/openai');
  const spy = jest.spyOn(openai, 'createOpenAI').mockReturnValue(() => ({}));
  LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should call createOpenAICompatible when model name does not contain gpt', () => {
  const compatible = require('@ai-sdk/openai-compatible');
  const spy = jest.spyOn(compatible, 'createOpenAICompatible').mockReturnValue(() => ({}));
  LlmProxyProvider.build('claude-3', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should use "none" as baseURL for createOpenAICompatible if connection url is missing', () => {
  const compatible = require('@ai-sdk/openai-compatible');
  const spy = jest.spyOn(compatible, 'createOpenAICompatible').mockReturnValue(() => ({}));
  LlmProxyProvider.build('claude-3', {
    connection: { key: 'key' } as any,
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  expect(spy).toHaveBeenCalledWith(expect.objectContaining({ baseURL: 'none' }));
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider and return a new instance', () => {
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned).not.toBe(provider);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same model', () => {
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.model).toBe('gpt-4');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same temperature', () => {
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.temperature).toBe(0.7);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same connection', () => {
  const connection = { key: 'key', url: 'url' };
  const provider = LlmProxyProvider.build('gpt-4', {
    connection,
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.connection).toEqual(connection);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with deep copied options', () => {
  const options = { a: 1 };
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    options,
    skills: [],
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.options).not.toBe(options);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with deep copied skills', () => {
  const skills = ['skill1'] as any;
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills,
    mcp: [],
  });
  const cloned = provider.clone();
  expect(cloned.skills).not.toBe(skills);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with deep copied mcp', () => {
  const mcp = ['mcp1'] as any;
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp,
  });
  const cloned = provider.clone();
  expect(cloned.mcp).not.toBe(mcp);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with fallback strategy if present', () => {
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
    fallback: { strategy: 'ordered', providers: [] } as any,
  });
  const cloned = provider.clone();
  expect(cloned.fallback?.strategy).toBe('ordered');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with deep copied fallback providers', () => {
  const fallback = { strategy: 'ordered', providers: ['p1'] } as any;
  const provider = LlmProxyProvider.build('gpt-4', {
    connection: { key: 'key', url: 'url' },
    temperature: 0.7,
    reasoning: 'medium',
    limit: 100,
    skills: [],
    mcp: [],
    fallback,
  });
  const cloned = provider.clone();
  expect(cloned.fallback?.providers).not.toBe(fallback.providers);
});
