import { PipelineLoopStepCompiler, PipelineLoopStep } from './loop';
import { PipelineStepCompilationError } from './errors';

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStepCompiler.limit should set the limit in the definition', () => {
  const compiler = PipelineLoopStepCompiler.build();
  compiler.limit(10);
  expect((compiler as any).definition.limit).toBe(10);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStepCompiler.condition should set the condition handler in the definition', () => {
  const compiler = PipelineLoopStepCompiler.build();
  const handler = jest.fn();
  compiler.condition(handler);
  expect((compiler as any).definition.condition).toBe(handler);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStepCompiler.action should set the action handler in the definition', () => {
  const compiler = PipelineLoopStepCompiler.build();
  const handler = jest.fn();
  compiler.action(handler);
  expect((compiler as any).definition.action).toBe(handler);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStepCompiler.action should return the compiler instance for chaining', () => {
  const compiler = PipelineLoopStepCompiler.build();
  const result = compiler.action(jest.fn());
  expect(result).toBe(compiler);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStepCompiler.compile should throw PipelineStepCompilationError if condition is missing', () => {
  const compiler = new PipelineLoopStepCompiler({ action: jest.fn() });
  expect(() => compiler.compile({} as any)).toThrow(PipelineStepCompilationError);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStepCompiler.compile should throw PipelineStepCompilationError if action is missing', () => {
  const compiler = new PipelineLoopStepCompiler({ condition: jest.fn() });
  expect(() => compiler.compile({} as any)).toThrow(PipelineStepCompilationError);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStepCompiler.compile should return a PipelineLoopStep instance when valid', () => {
  const compiler = new PipelineLoopStepCompiler({
    condition: jest.fn(),
    action: jest.fn(),
  });
  const step = compiler.compile({ pipeline: {}, parent: {} } as any);
  expect(step).toBeInstanceOf(PipelineLoopStep);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStep.run should return fulfilled status when condition returns fulfilled', async () => {
  const condition = jest.fn().mockResolvedValue({ status: 'fulfilled' });
  const action = jest.fn().mockResolvedValue({
    compile: jest.fn().mockResolvedValue({
      run: jest.fn().mockResolvedValue('test-value'),
    }),
  });
  const step = new PipelineLoopStep('loop', <any>{
    condition,
    action,
    pipeline: { session: { emit: jest.fn() } } as any,
  });
  const params = { extend: jest.fn().mockReturnThis() } as any;
  const result = await step.run(params);
  expect(result.status).toBe('fulfilled');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStep.run should return voided status when loop limit is reached', async () => {
  const condition = jest.fn().mockResolvedValue({ status: 'pending' });
  const action = jest.fn().mockResolvedValue({
    compile: jest.fn().mockResolvedValue({
      run: jest.fn().mockResolvedValue('test-value'),
    }),
  });
  const step = new PipelineLoopStep('loop', <any>{
    condition,
    action,
    limit: 2,
    pipeline: { session: { emit: jest.fn() } } as any,
  });
  const params = { extend: jest.fn().mockReturnThis() } as any;
  const result = await step.run(params);
  expect(result.status).toBe('voided');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStep.run should return rejected status when condition handler rejects', async () => {
  const condition = jest.fn().mockRejectedValue(new Error('condition failed'));
  const action = jest.fn().mockResolvedValue({
    compile: jest.fn().mockResolvedValue({
      run: jest.fn().mockResolvedValue('test-value'),
    }),
  });
  const step = new PipelineLoopStep('loop', <any>{
    condition,
    action,
    pipeline: { session: { emit: jest.fn() } } as any,
  });
  const params = { extend: jest.fn().mockReturnThis() } as any;
  const result = await step.run(params);
  expect(result.status).toBe('rejected');
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStep.run should call action handler multiple times if condition is pending', async () => {
  const condition = jest
    .fn()
    .mockResolvedValueOnce({ status: 'pending' })
    .mockResolvedValueOnce({ status: 'fulfilled' });
  const action = jest.fn().mockResolvedValue({
    compile: jest.fn().mockResolvedValue({
      run: jest.fn().mockResolvedValue('test-value'),
    }),
  });
  const step = new PipelineLoopStep('loop', <any>{
    condition,
    action,
    pipeline: { session: { emit: jest.fn() } } as any,
  });
  const params = { extend: jest.fn().mockReturnThis() } as any;
  await step.run(params);
  expect(action).toHaveBeenCalledTimes(2);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineLoopStep.run should emit step:run event at the start of execution', async () => {
  const emit = jest.fn();
  const step = new PipelineLoopStep('loop', <any>{
    condition: jest.fn().mockResolvedValue({ status: 'fulfilled' }),
    action: jest.fn().mockResolvedValue({ compile: jest.fn().mockResolvedValue({ run: jest.fn() }) }),
    pipeline: { session: { emit } } as any,
  });
  await step.run({ extend: jest.fn().mockReturnThis() } as any);
  expect(emit).toHaveBeenCalledWith('step:run', expect.objectContaining({ step }));
});
