import { PipelineStep, PipelineStepCompiler, IPipelineStepSource } from './model';
import { Pipeline } from '../model';

/* Generated by @n1k1t/unit-generator */
it('should set the title from definition if provided', () => {
  class MockStep extends PipelineStep {
    public async run() {
      return {};
    }
  }
  const pipeline = {} as Pipeline;
  const step = new MockStep('test' as any, { pipeline, parent: pipeline, title: 'Custom Title' });
  expect(step.title).toBe('Custom Title');
});

/* Generated by @n1k1t/unit-generator */
it('should generate a default title if not provided in definition', () => {
  class MockStep extends PipelineStep {
    public async run() {
      return {};
    }
  }
  const pipeline = {} as Pipeline;
  const step = new MockStep('test' as any, { pipeline, parent: pipeline });
  expect(step.title).toMatch(/^Step \d+$/);
});

/* Generated by @n1k1t/unit-generator */
it('should assign the pipeline from definition', () => {
  class MockStep extends PipelineStep {
    public async run() {
      return {};
    }
  }
  const pipeline = { id: 'pipe-1' } as any;
  const step = new MockStep('test' as any, { pipeline, parent: pipeline });
  expect(step.pipeline).toBe(pipeline);
});

/* Generated by @n1k1t/unit-generator */
it('should assign the parent from definition', () => {
  class MockStep extends PipelineStep {
    public async run() {
      return {};
    }
  }
  const pipeline = {} as Pipeline;
  const parent = { id: 'parent-1' } as any;
  const step = new MockStep('test' as any, { pipeline, parent });
  expect(step.parent).toBe(parent);
});

/* Generated by @n1k1t/unit-generator */
it('should return an array containing only itself in trace if parent is missing', () => {
  class MockStep extends PipelineStep {
    public async run() {
      return {};
    }
  }
  const pipeline = {} as Pipeline;
  const step = new MockStep('test' as any, { pipeline, parent: null as any });
  expect(step.trace()).toEqual([step]);
});

/* Generated by @n1k1t/unit-generator */
it('should call trace on parent and concatenate results in trace method', () => {
  class MockStep extends PipelineStep {
    public async run() {
      return {};
    }
  }
  const pipeline = {} as Pipeline;
  const parent = { trace: () => ['parent-trace'] } as any;
  const step = new MockStep('test' as any, { pipeline, parent });
  expect(step.trace()).toEqual([step, 'parent-trace']);
});

/* Generated by @n1k1t/unit-generator */
it('should allow creating a concrete implementation of PipelineStepCompiler', () => {
  class MockCompiler extends PipelineStepCompiler {
    public compile(provided: IPipelineStepSource) {
      return {} as any;
    }
  }
  const compiler = new MockCompiler();
  expect(compiler).toBeDefined();
});
