import { z } from 'zod';

import { PipelineSelfStepCompiler, PipelineSelfStep } from './self';
import { PipelineStepCompilationError } from '../errors';

/* Generated by @n1k1t/unit-generator */
it('PipelineSelfStepCompiler.build should return an instance of PipelineSelfStepCompiler', () => {
  const compiler = PipelineSelfStepCompiler.build('test-step');
  expect(compiler).toBeInstanceOf(PipelineSelfStepCompiler);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineSelfStepCompiler.compile should throw PipelineStepCompilationError if exec is not provided', () => {
  const compiler = PipelineSelfStepCompiler.build('test-step');
  expect(() => compiler.compile({} as any)).toThrow(PipelineStepCompilationError);
});

/* Generated by @n1k1t/unit-generator */
it('PipelineSelfStepCompiler.compile should return a PipelineSelfStep instance when exec is provided', () => {
  const compiler = PipelineSelfStepCompiler.build('test-step').exec(async () => 'result');
  const step = compiler.compile({ pipeline: { session: { emit: jest.fn() } } } as any);
  expect(step).toBeInstanceOf(PipelineSelfStep);
});

/* Generated by @n1k1t/unit-generator */
it('should set the type to "self" upon instantiation of PipelineSelfStepCompiler', () => {
  const compiler = new PipelineSelfStepCompiler({});
  expect((compiler as any).type).toBe('self');
});

/* Generated by @n1k1t/unit-generator */
it('should emit "step:run" event when PipelineSelfStep starts execution', async () => {
  const emit = jest.fn();
  const compiler = PipelineSelfStepCompiler.build().exec(async () => ({}));
  const step = compiler.compile({ pipeline: { session: { emit } } } as any);
  await step.run({} as any);
  expect(emit).toHaveBeenCalledWith('step:run', expect.objectContaining({ step }));
});

/* Generated by @n1k1t/unit-generator */
it('should call the schema function with parameters if schema is a function', async () => {
  const schemaFn = jest.fn().mockResolvedValue(z.any());
  const compiler = PipelineSelfStepCompiler.build()
    .schema(schemaFn)
    .exec(async () => ({}));
  const step = compiler.compile({ pipeline: { session: { emit: jest.fn() } } } as any);
  const params = { config: {} } as any;
  await step.run(params);
  expect(schemaFn).toHaveBeenCalledWith(params);
});

/* Generated by @n1k1t/unit-generator */
it('should call parseAsync on the schema with the execution result', async () => {
  const schema = { parseAsync: jest.fn().mockResolvedValue({}) };
  const compiler = PipelineSelfStepCompiler.build()
    .schema(schema as any)
    .exec(async () => 'result');
  const step = compiler.compile({ pipeline: { session: { emit: jest.fn() } } } as any);
  await step.run({} as any);
  expect(schema.parseAsync).toHaveBeenCalledWith('result');
});

/* Generated by @n1k1t/unit-generator */
it('should rethrow the error when execution fails in PipelineSelfStep', async () => {
  const error = new Error('execution failed');
  const compiler = PipelineSelfStepCompiler.build().exec(async () => {
    throw error;
  });
  const step = compiler.compile({ pipeline: { session: { emit: jest.fn() } } } as any);
  await expect(step.run({} as any)).rejects.toThrow(error);
});
