import { PipelineSwarmStepCompiler, PipelineSwarmStep } from './swarm';
import { PipelineStepCompilationError } from '../errors';
import { PipelineStep } from './model';

/* Generated by @n1k1t/unit-generator */
it('should create a PipelineSwarmStepCompiler instance with title via build', () => {
  const compiler = PipelineSwarmStepCompiler.build('test title');
  expect(compiler).toBeInstanceOf(PipelineSwarmStepCompiler);
});

/* Generated by @n1k1t/unit-generator */
it('should set subtasks and return the compiler instance', () => {
  const compiler = PipelineSwarmStepCompiler.build();
  const subtasks: any[] = [];
  const result = compiler.list(subtasks);
  expect(result).toBe(compiler);
});

/* Generated by @n1k1t/unit-generator */
it('should set limit and return the compiler instance', () => {
  const compiler = PipelineSwarmStepCompiler.build();
  const result = compiler.limit(5);
  expect(result).toBe(compiler);
});

/* Generated by @n1k1t/unit-generator */
it('should throw PipelineStepCompilationError if subtasks are not provided during compile', () => {
  const compiler = PipelineSwarmStepCompiler.build();
  expect(() => compiler.compile({} as any)).toThrow(PipelineStepCompilationError);
});

/* Generated by @n1k1t/unit-generator */
it('should return a PipelineSwarmStep instance when compile is called with subtasks', () => {
  const compiler = PipelineSwarmStepCompiler.build().list([]);
  const step = compiler.compile({ pipeline: {} as any, parent: {} as any });
  expect(step).toBeInstanceOf(PipelineSwarmStep);
});

/* Generated by @n1k1t/unit-generator */
it('should store the limit in the definition after compilation', () => {
  const compiler = PipelineSwarmStepCompiler.build().limit(10).list([]);
  const step = compiler.compile({ pipeline: {} as any, parent: {} as any });
  expect((step as any).definition.limit).toBe(10);
});

/* Generated by @n1k1t/unit-generator */
it('should store the subtasks in the definition after compilation', () => {
  const subtasks: any[] = [{}];
  const compiler = PipelineSwarmStepCompiler.build().list(subtasks);
  const step = compiler.compile({ pipeline: {} as any, parent: {} as any });
  expect((step as any).definition.list).toBe(subtasks);
});

/* Generated by @n1k1t/unit-generator */
it('should emit step:run event with INIT state when run is called', async () => {
  const emit = jest.fn();
  const pipeline = { session: { emit } };
  const step = new PipelineSwarmStep('swarm', { list: [], pipeline: pipeline as any, parent: pipeline as any });
  await step.run({} as any);
  expect(emit).toHaveBeenCalledWith(
    'step:run',
    expect.objectContaining({ meta: expect.objectContaining({ state: 'INIT' }) }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should call subtasks function with parameters if subtasks is a function', async () => {
  const subtasksFn = jest.fn().mockResolvedValue([]);
  const pipeline = { session: { emit: jest.fn() } };
  const step = new PipelineSwarmStep('swarm', {
    list: subtasksFn,
    pipeline: pipeline as any,
    parent: pipeline as any,
  });
  const parameters = { foo: 'bar' } as any;
  await step.run(parameters);
  expect(subtasksFn).toHaveBeenCalledWith(parameters);
});

/* Generated by @n1k1t/unit-generator */
it('should compile subtasks if they are compilers', async () => {
  const subtaskStep = { run: jest.fn().mockResolvedValue('result') };
  const subtaskCompiler = { compile: jest.fn().mockResolvedValue(subtaskStep) };
  const pipeline = { session: { emit: jest.fn() } };
  const step = new PipelineSwarmStep('swarm', {
    list: [subtaskCompiler as any],
    pipeline: pipeline as any,
    parent: pipeline as any,
  });
  await step.run({} as any);
  expect(subtaskCompiler.compile).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should run subtasks and pass parameters if they are PipelineStep instances', async () => {
  const subtaskStep = Object.create(PipelineStep.prototype);
  subtaskStep.run = jest.fn().mockResolvedValue('result');
  const subtaskCompiler = { compile: jest.fn().mockResolvedValue(subtaskStep) };
  const pipeline = { session: { emit: jest.fn() } };
  const step = new PipelineSwarmStep('swarm', {
    list: [subtaskCompiler as any],
    pipeline: pipeline as any,
    parent: pipeline as any,
  });
  const parameters = { baz: 'qux' } as any;
  await step.run(parameters);
  expect(subtaskStep.run).toHaveBeenCalledWith(parameters);
});

/* Generated by @n1k1t/unit-generator */
it('should run subtasks with undefined if they are not PipelineStep instances', async () => {
  const subtaskPipeline = { run: jest.fn().mockResolvedValue('result') };
  const subtaskCompiler = { compile: jest.fn().mockResolvedValue(subtaskPipeline) };
  const pipeline = { session: { emit: jest.fn() } };
  const step = new PipelineSwarmStep('swarm', {
    list: [subtaskCompiler as any],
    pipeline: pipeline as any,
    parent: pipeline as any,
  });
  await step.run({} as any);
  expect(subtaskPipeline.run).toHaveBeenCalledWith(undefined);
});

/* Generated by @n1k1t/unit-generator */
it('should return an array of PromiseSettledResult from subtasks', async () => {
  const subtaskStep = { run: jest.fn().mockResolvedValue('res') };
  const subtaskCompiler = { compile: jest.fn().mockResolvedValue(subtaskStep) };
  const pipeline = { session: { emit: jest.fn() } };
  const step = new PipelineSwarmStep('swarm', {
    list: [subtaskCompiler as any],
    pipeline: pipeline as any,
    parent: pipeline as any,
  });
  const results = await step.run({} as any);
  expect(results).toEqual([{ status: 'fulfilled', value: 'res' }]);
});

/* Generated by @n1k1t/unit-generator */
it('should emit step:run event with DONE state when run completes successfully', async () => {
  const emit = jest.fn();
  const pipeline = { session: { emit } };
  const step = new PipelineSwarmStep('swarm', { list: [], pipeline: pipeline as any, parent: pipeline as any });
  await step.run({} as any);
  expect(emit).toHaveBeenLastCalledWith(
    'step:run',
    expect.objectContaining({ meta: expect.objectContaining({ state: 'DONE' }) }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should emit step:run event with ERROR state and rethrow error when subtasks function fails', async () => {
  const emit = jest.fn();
  const pipeline = { session: { emit } };
  const subtasksFn = jest.fn().mockRejectedValue(new Error('fail'));
  const step = new PipelineSwarmStep('swarm', {
    list: subtasksFn,
    pipeline: pipeline as any,
    parent: pipeline as any,
  });
  await expect(step.run({} as any)).rejects.toThrow('fail');
  expect(emit).toHaveBeenLastCalledWith(
    'step:run',
    expect.objectContaining({ meta: expect.objectContaining({ state: 'ERROR' }) }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should return the compiler instance when calling list', () => {
  const compiler = PipelineSwarmStepCompiler.build();
  const result = compiler.list([]);
  expect(result).toBe(compiler);
});

/* Generated by @n1k1t/unit-generator */
it('should set the map definition when calling map', () => {
  const compiler = PipelineSwarmStepCompiler.build();
  const map = { task: {} as any };
  compiler.map(map);
  expect((compiler as any).definition.map).toBe(map);
});

/* Generated by @n1k1t/unit-generator */
it('should return the compiler instance when calling map', () => {
  const compiler = PipelineSwarmStepCompiler.build();
  const result = compiler.map({});
  expect(result).toBe(compiler);
});

/* Generated by @n1k1t/unit-generator */
it('should throw a conflict error during compilation if both list and map are defined', () => {
  const compiler = PipelineSwarmStepCompiler.build();
  compiler.list([]);
  compiler.map({});
  const source = { pipeline: { session: { emit: jest.fn() } } } as any;
  expect(() => compiler.compile(source)).toThrow(PipelineStepCompilationError);
});

/* Generated by @n1k1t/unit-generator */
it('should call run on compiled subtask with parameters when it is an instance of PipelineStep', async () => {
  const mockRun = jest.fn().mockResolvedValue('val');
  const mockCompiled = Object.create(PipelineStep.prototype);
  mockCompiled.run = mockRun;
  const subtask = { compile: jest.fn().mockResolvedValue(mockCompiled) };
  const compiler = PipelineSwarmStepCompiler.build().list([subtask as any]);
  const step = compiler.compile({ pipeline: { session: { emit: jest.fn() } } } as any);
  const parameters = { foo: 'bar' } as any;

  await step.run(parameters);

  expect(mockRun).toHaveBeenCalledWith(parameters);
});

/* Generated by @n1k1t/unit-generator */
it('should call run on compiled subtask with undefined when it is not an instance of PipelineStep', async () => {
  const mockRun = jest.fn().mockResolvedValue('val');
  const mockCompiled = { run: mockRun };
  const subtask = { compile: jest.fn().mockResolvedValue(mockCompiled) };
  const compiler = PipelineSwarmStepCompiler.build().list([subtask as any]);
  const step = compiler.compile({ pipeline: { session: { emit: jest.fn() } } } as any);

  await step.run({} as any);

  expect(mockRun).toHaveBeenCalledWith(undefined);
});

/* Generated by @n1k1t/unit-generator */
it('should emit "step:run" event when starting execution', async () => {
  const emit = jest.fn();
  const compiler = PipelineSwarmStepCompiler.build().list([]);
  const step = compiler.compile({ pipeline: { session: { emit } } } as any);

  await step.run({} as any);

  expect(emit).toHaveBeenCalledWith('step:run', expect.objectContaining({ step }));
});

/* Generated by @n1k1t/unit-generator */
it('should resolve subtasks from a function when map is a function in run', async () => {
  const subtask = { compile: jest.fn().mockResolvedValue({ run: jest.fn().mockResolvedValue('val') }) };
  const compiler = PipelineSwarmStepCompiler.build().map(() => ({ key: subtask as any }));
  const step = compiler.compile({ pipeline: { session: { emit: jest.fn() } } } as any);
  const result = await step.run({} as any);
  expect(result).toEqual({ key: { status: 'fulfilled', value: 'val' } });
});

/* Generated by @n1k1t/unit-generator */
it('should return a record of settled results when map is used in run', async () => {
  const subtask = { compile: jest.fn().mockResolvedValue({ run: jest.fn().mockResolvedValue('val') }) };
  const compiler = PipelineSwarmStepCompiler.build().map({ key: subtask as any });
  const step = compiler.compile({ pipeline: { session: { emit: jest.fn() } } } as any);
  const result = await step.run({} as any);
  expect(result).toEqual({ key: { status: 'fulfilled', value: 'val' } });
});

/* Generated by @n1k1t/unit-generator */
it('should emit step:run event with done meta when map execution finishes', async () => {
  const emit = jest.fn();
  const subtask = { compile: jest.fn().mockResolvedValue({ run: jest.fn().mockResolvedValue('val') }) };
  const compiler = PipelineSwarmStepCompiler.build().map({ key: subtask as any });
  const step = compiler.compile({ pipeline: { session: { emit } } } as any);
  await step.run({} as any);
  expect(emit).toHaveBeenCalledWith('step:run', expect.objectContaining({ meta: expect.anything() }));
});
