import { APICallError, NoObjectGeneratedError } from 'ai';
import { PipelineAiError } from './errors';

/* Generated by @n1k1t/unit-generator */
it('should set the type property from constructor', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  expect(error.type).toBe('EMPTY_OUTPUT');
});

/* Generated by @n1k1t/unit-generator */
it('should set the llm property from constructor', () => {
  const llm = { provider: 'openai' } as any;
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm });
  expect(error.llm).toBe(llm);
});

/* Generated by @n1k1t/unit-generator */
it('should set the reason property from constructor', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any, reason: 'test reason' });
  expect(error.reason).toBe('test reason');
});

/* Generated by @n1k1t/unit-generator */
it('should set the default reason to "none" if not provided in constructor', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  expect(error.reason).toBe('none');
});

/* Generated by @n1k1t/unit-generator */
it('should set the correct error message in constructor', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any, reason: 'test' });
  expect(error.message).toBe('Got error [EMPTY_OUTPUT] while generation. Reason: test');
});

/* Generated by @n1k1t/unit-generator */
it('should return true when is() is called with matching type', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  expect(error.is(['EMPTY_OUTPUT'])).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should return false when is() is called with non-matching type', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  expect(error.is(['WRONG_RESPONSE'])).toBe(false);
});

/* Generated by @n1k1t/unit-generator */
it('should update type when assign() is called with a type', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  error.assign({ type: 'WRONG_RESPONSE' });
  expect(error.type).toBe('WRONG_RESPONSE');
});

/* Generated by @n1k1t/unit-generator */
it('should update sequence when assign() is called with a non-empty sequence', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  const sequence = [new PipelineAiError({ type: 'BAD_API_CALL', llm: {} as any })];
  error.assign({ sequence });
  expect(error.sequence).toBe(sequence);
});

/* Generated by @n1k1t/unit-generator */
it('should return the same instance from assign()', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  const result = error.assign({ type: 'WRONG_RESPONSE' });
  expect(result).toBe(error);
});

/* Generated by @n1k1t/unit-generator */
it('should return an array containing only itself when research() is called on error without sequence', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  expect(error.research()).toEqual([error]);
});

/* Generated by @n1k1t/unit-generator */
it('should return unique errors in reverse order when research() is called on error with sequence', () => {
  const error1 = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  const error2 = new PipelineAiError({ type: 'WRONG_RESPONSE', llm: {} as any, sequence: [error1] });
  expect(error2.research()).toEqual([error2, error1]);
});

/* Generated by @n1k1t/unit-generator */
it('should return unique errors in research() when duplicates exist in sequence', () => {
  const error1 = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  const error2 = new PipelineAiError({ type: 'WRONG_RESPONSE', llm: {} as any, sequence: [error1, error1] });
  expect(error2.research()).toEqual([error2, error1]);
});

/* Generated by @n1k1t/unit-generator */
it('should create a new instance using build() static method', () => {
  const error = PipelineAiError.build({ type: 'EMPTY_OUTPUT', llm: {} as any });
  expect(error).toBeInstanceOf(PipelineAiError);
});

/* Generated by @n1k1t/unit-generator */
it('should return the same instance in convert() if source is already a PipelineAiError', () => {
  const error = new PipelineAiError({ type: 'EMPTY_OUTPUT', llm: {} as any });
  expect(PipelineAiError.convert({ source: error, llm: {} as any })).toBe(error);
});

/* Generated by @n1k1t/unit-generator */
it('should convert APICallError to BAD_API_CALL type in convert()', () => {
  const source = { message: 'api error' };
  const spy = jest.spyOn(APICallError, 'isInstance').mockReturnValue(true);
  const result = PipelineAiError.convert({ source, llm: {} as any });
  expect(result.type).toBe('BAD_API_CALL');
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should convert NoObjectGeneratedError to WRONG_RESPONSE type in convert()', () => {
  const source = { message: 'no object' };
  const spy = jest.spyOn(NoObjectGeneratedError, 'isInstance').mockReturnValue(true);
  const result = PipelineAiError.convert({ source, llm: {} as any });
  expect(result.type).toBe('WRONG_RESPONSE');
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should use source message as reason in convert() for generic Error', () => {
  const source = new Error('generic error');
  const error = PipelineAiError.convert({ source, llm: {} as any });
  expect(error.reason).toBe('generic error');
});

/* Generated by @n1k1t/unit-generator */
it('should use string source as reason in convert()', () => {
  const error = PipelineAiError.convert({ source: 'string error', llm: {} as any });
  expect(error.reason).toBe('string error');
});

/* Generated by @n1k1t/unit-generator */
it('should use message property from object source in convert()', () => {
  const error = PipelineAiError.convert({ source: { message: 'object message' }, llm: {} as any });
  expect(error.reason).toBe('object message');
});

/* Generated by @n1k1t/unit-generator */
it('should set source property in convert() when source is an Error', () => {
  const source = new Error('test');
  const error = PipelineAiError.convert({ source, llm: {} as any });
  expect(error.source).toBe(source);
});
