import { LlmToolsFactory, LlmSkillsFactory } from './factory';
import * as tools from './tools';

/* Generated by @n1k1t/unit-generator */
it('LlmToolsFactory.build should return an instance of LlmToolsFactory', () => {
  expect(LlmToolsFactory.build()).toBeInstanceOf(LlmToolsFactory);
});

/* Generated by @n1k1t/unit-generator */
it('LlmToolsFactory.provide should return an empty object by default', () => {
  expect(LlmToolsFactory.build().provide()).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('LlmToolsFactory.all should include all tools', () => {
  expect(LlmToolsFactory.build().all().provide()).toEqual(tools);
});

/* Generated by @n1k1t/unit-generator */
it('LlmToolsFactory.web should include search and fetch tools', () => {
  const provided = LlmToolsFactory.build().web().provide();
  expect(provided).toEqual({
    search: tools.search,
    fetch: tools.fetch,
  });
});

/* Generated by @n1k1t/unit-generator */
it('LlmToolsFactory.files should include read-only tools when mode is read', () => {
  const provided = LlmToolsFactory.build().files('read').provide();
  expect(provided).toEqual({
    grep: tools.grep,
    glob: tools.glob,
    read: tools.read,
    ls: tools.ls,
  });
});

/* Generated by @n1k1t/unit-generator */
it('LlmToolsFactory.files should include write tools when mode is read-write', () => {
  const provided = LlmToolsFactory.build().files('read-write').provide();
  expect(provided.mkdir).toBe(tools.mkdir);
});

/* Generated by @n1k1t/unit-generator */
it('LlmToolsFactory.commands should include specified tools', () => {
  const provided = LlmToolsFactory.build().commands(['npm']).provide();
  expect(provided.npm).toBe(tools.npm);
});

/* Generated by @n1k1t/unit-generator */
it('LlmToolsFactory.custom should merge custom tools into included', () => {
  const customTool = {} as any;
  const provided = LlmToolsFactory.build().custom({ myTool: customTool }).provide();
  expect(provided.myTool).toBe(customTool);
});

/* Generated by @n1k1t/unit-generator */
it('LlmSkillsFactory.build should return an instance of LlmSkillsFactory', () => {
  expect(LlmSkillsFactory.build()).toBeInstanceOf(LlmSkillsFactory);
});

/* Generated by @n1k1t/unit-generator */
it('LlmSkillsFactory.register should parse and store skill from markdown', () => {
  const factory = LlmSkillsFactory.build();
  const raw = '---\nname: test-skill\ndescription: test-desc\n---\ncontent-body';
  factory.register(raw);
  expect(factory.all().provide()).toContainEqual({
    name: 'test-skill',
    description: 'test-desc',
    content: 'content-body',
  });
});

/* Generated by @n1k1t/unit-generator */
it('LlmSkillsFactory.provide should return an array of included skills', () => {
  const skill = { name: 's1', description: 'd1', content: 'c1' };
  const factory = LlmSkillsFactory.build().custom([skill]);
  expect(factory.provide()).toEqual([skill]);
});

/* Generated by @n1k1t/unit-generator */
it('LlmSkillsFactory.custom should add skills to the included list', () => {
  const skill = { name: 'custom', description: 'desc', content: 'cont' };
  const factory = LlmSkillsFactory.build().custom([skill]);
  expect(factory.provide()).toContain(skill);
});
