import { LlmMcp, LlmMcpClient } from './mcp';

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.build should return an instance of LlmMcp', () => {
  const config = { transport: {} as any };
  expect(LlmMcp.build(config)).toBeInstanceOf(LlmMcp);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.clone should return a new instance of LlmMcp', () => {
  const mcp = LlmMcp.build({ transport: {} as any });
  expect(mcp.clone()).not.toBe(mcp);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.clone should copy the transport configuration', () => {
  const transport = { type: 'stdio' } as any;
  const mcp = LlmMcp.build({ transport });
  expect(mcp.clone().configuration.transport).toBe(transport);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.clone should copy the enabled tools array', () => {
  const enabled = ['tool1'];
  const mcp = LlmMcp.build({ transport: {} as any, tools: { enabled } });
  expect(mcp.clone().configuration.tools?.enabled).toEqual(enabled);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.clone should create a new array instance for enabled tools', () => {
  const enabled = ['tool1'];
  const mcp = LlmMcp.build({ transport: {} as any, tools: { enabled } });
  expect(mcp.clone().configuration.tools?.enabled).not.toBe(enabled);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.clone should copy the disabled tools array', () => {
  const disabled = ['tool2'];
  const mcp = LlmMcp.build({ transport: {} as any, tools: { disabled } });
  expect(mcp.clone().configuration.tools?.disabled).toEqual(disabled);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.clone should initialize tools as an empty object if not present', () => {
  const mcp = LlmMcp.build({ transport: {} as any });
  expect(mcp.clone().configuration.tools).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.assign should return a new instance with updated tools', () => {
  const mcp = LlmMcp.build({ transport: {} as any });
  const tools = { enabled: ['new'] };
  expect(mcp.assign({ tools }).configuration.tools).toEqual(tools);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcp.assign should not modify the original instance configuration', () => {
  const mcp = LlmMcp.build({ transport: {} as any, tools: { enabled: ['old'] } });
  mcp.assign({ tools: { enabled: ['new'] } });
  expect(mcp.configuration.tools?.enabled).toEqual(['old']);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcpClient.build should return an instance of LlmMcpClient', () => {
  const source = {} as any;
  const config = { transport: {} as any };
  expect(LlmMcpClient.build(source, config)).toBeInstanceOf(LlmMcpClient);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcpClient.tools should return all tools when no filters are provided', async () => {
  const tools = { t1: {}, t2: {} };
  const source = { tools: jest.fn().mockResolvedValue(tools) } as any;
  const client = LlmMcpClient.build(source, { transport: {} as any });
  const result = await client.tools();
  expect(result).toEqual(tools);
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcpClient.tools should filter tools by enabled patterns using minimatch', async () => {
  const tools = { 'test:1': {}, 'other:2': {} };
  const source = { tools: jest.fn().mockResolvedValue(tools) } as any;
  const client = LlmMcpClient.build(source, { transport: {} as any, tools: { enabled: ['test:*'] } });
  const result = await client.tools();
  expect(result).toEqual({ 'test:1': {} });
});

/* Generated by @n1k1t/unit-generator */
it('LlmMcpClient.close should call the close method on the source client', async () => {
  const source = { close: jest.fn().mockResolvedValue(undefined) } as any;
  const client = LlmMcpClient.build(source, { transport: {} as any });
  await client.close();
  expect(source.close).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should iterate over tools to apply filtering when disabled tools are configured', async () => {
  const mockSource = {
    tools: jest.fn().mockResolvedValue({ tool1: {} }),
    close: jest.fn(),
  };
  const client = LlmMcpClient.build(mockSource as any, {
    transport: {} as any,
    tools: { enabled: ['tool1'], disabled: ['any'] },
  });

  const result = await client.tools();

  expect(result).toEqual({});
});
