import { LlmRouter } from './router';

import * as providers from './providers';
import env from '../../env';

/* Generated by @n1k1t/unit-generator */
it('LlmRouter.build should return an instance of LlmRouter', () => {
  expect(LlmRouter.build()).toBeInstanceOf(LlmRouter);
});

/* Generated by @n1k1t/unit-generator */
it('provide should call LlmOpenaiProvider.build when model name contains gpt', () => {
  const spy = jest.spyOn(providers.LlmOpenaiProvider, 'build');
  new LlmRouter({ key: 'test' }).provide('gpt-4o');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should call LlmAnthropicProvider.build when model name contains claude', () => {
  const spy = jest.spyOn(providers.LlmAnthropicProvider, 'build');
  new LlmRouter({ key: 'test' }).provide('claude-3-5-sonnet');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should call LlmGoogleProvider.build when model name contains gemini', () => {
  const spy = jest.spyOn(providers.LlmGoogleProvider, 'build');
  new LlmRouter({ key: 'test' }).provide('gemini-1.5-flash');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should call LlmMistralProvider.build when model name contains mistral', () => {
  const spy = jest.spyOn(providers.LlmMistralProvider, 'build');
  new LlmRouter({ key: 'test' }).provide('mistral-large-latest');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should call LlmMistralProvider.build when model name contains pixtral', () => {
  const spy = jest.spyOn(providers.LlmMistralProvider, 'build');
  new LlmRouter({ key: 'test' }).provide('pixtral-12b');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should call LlmOpenaiProvider.build by default for unknown models', () => {
  const spy = jest.spyOn(providers.LlmOpenaiProvider, 'build');
  new LlmRouter({ key: 'test' }).provide('unknown-model-name');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should use the provider specified in configuration regardless of model name', () => {
  const spy = jest.spyOn(providers.LlmAnthropicProvider, 'build');
  new LlmRouter({ key: 'test', provider: 'anthropic' }).provide('gpt-4');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should call LlmProxyProvider.build when provider is set to proxy', () => {
  const spy = jest.spyOn(providers.LlmProxyProvider, 'build');
  new LlmRouter({ key: 'test', provider: 'proxy' }).provide('any-model');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should fall back to model-based definition if configuration provider is not recognized', () => {
  const spy = jest.spyOn(providers.LlmMistralProvider, 'build');
  new LlmRouter({ key: 'test', provider: 'invalid-provider' }).provide('mistral-tiny');
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should use env.model as the default model name when none is provided', () => {
  const spy = jest.spyOn(providers.LlmOpenaiProvider, 'build');
  new LlmRouter({ key: 'test', provider: 'openai' }).provide();
  expect(spy).toHaveBeenCalledWith(env.model, expect.any(Object));
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('provide should pass the configuration to the provider build method', () => {
  const config = { key: 'test-key', provider: 'openai' };
  const spy = jest.spyOn(providers.LlmOpenaiProvider, 'build');
  new LlmRouter(config).provide('gpt-4');
  expect(spy).toHaveBeenCalledWith('gpt-4', { connection: config });
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('static build should use env.key as the default key when no options are provided', () => {
  const router = LlmRouter.build();
  expect((router as any).configuration.key).toBe(env.key ?? 'none');
});

/* Generated by @n1k1t/unit-generator */
it('static build should use the provided key option', () => {
  const router = LlmRouter.build({ key: 'custom-key' });
  expect((router as any).configuration.key).toBe('custom-key');
});

/* Generated by @n1k1t/unit-generator */
it('static build should use env.url as the default url', () => {
  const router = LlmRouter.build();
  expect((router as any).configuration.url).toBe(env.url);
});
