import path from 'path';
import fs from 'fs/promises';

import { File, FileReplaceError, FileBuildError } from './file';

/* Generated by @n1k1t/unit-generator */
it('should correctly compute the directory from the file path', () => {
  const file = new File({ cwd: '/app', path: 'src/models/file.ts', lang: 'ts', content: '' });
  expect(file.dir).toBe('src/models');
});

/* Generated by @n1k1t/unit-generator */
it('should store the provided current working directory', () => {
  const file = new File({ cwd: '/custom/cwd', path: 'file.ts', lang: 'ts', content: '' });
  expect(file.cwd).toBe('/custom/cwd');
});

/* Generated by @n1k1t/unit-generator */
it('should append content with a newline separator', () => {
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'line1' });
  file.append('line2');
  expect(file.content).toBe('line1\nline2');
});

/* Generated by @n1k1t/unit-generator */
it('should not modify content when appending an empty string', () => {
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'line1' });
  file.append('');
  expect(file.content).toBe('line1');
});

/* Generated by @n1k1t/unit-generator */
it('should prepend content with a newline separator', () => {
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'line2' });
  file.prepend('line1');
  expect(file.content).toBe('line1\nline2');
});

/* Generated by @n1k1t/unit-generator */
it('should not modify content when prepending an empty string', () => {
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'line1' });
  file.prepend('');
  expect(file.content).toBe('line1');
});

/* Generated by @n1k1t/unit-generator */
it('should replace all occurrences of the source string when not in strict mode', () => {
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'aba' });
  file.replace('a', 'c');
  expect(file.content).toBe('cbc');
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileReplaceError when the source string is missing in strict mode', () => {
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'abc', options: { strict: true } });
  expect(() => file.replace('z', 'x')).toThrow(FileReplaceError);
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileReplaceError when multiple occurrences are found in strict mode', () => {
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'aba' });
  expect(() => file.replace('a', 'c', { strict: true })).toThrow(FileReplaceError);
});

/* Generated by @n1k1t/unit-generator */
it('should call fs.writeFile with the correct path and content during write', async () => {
  const writeFileSpy = jest.spyOn(fs, 'writeFile').mockResolvedValue(undefined);
  jest.spyOn(fs, 'mkdir').mockResolvedValue(undefined as any);
  const file = new File({ cwd: '/app', path: 'src/test.ts', lang: 'ts', content: 'data' });
  await file.write();
  expect(writeFileSpy).toHaveBeenCalledWith(path.join('/app', 'src/test.ts'), 'data', 'utf8');
});

/* Generated by @n1k1t/unit-generator */
it('should update the content property if a value is provided to the write method', async () => {
  jest.spyOn(fs, 'mkdir').mockResolvedValue(undefined as any);
  jest.spyOn(fs, 'writeFile').mockResolvedValue(undefined);
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'old' });
  await file.write('new');
  expect(file.content).toBe('new');
});

/* Generated by @n1k1t/unit-generator */
it('should update the content property from the file system when refresh is called', async () => {
  jest.spyOn(fs, 'readFile').mockResolvedValue('new content');
  const file = new File({ cwd: '/app', path: 'test.ts', lang: 'ts', content: 'old' });
  await file.refresh();
  expect(file.content).toBe('new content');
});

/* Generated by @n1k1t/unit-generator */
it('should call fs.rm with the correct path during remove', async () => {
  const rmSpy = jest.spyOn(fs, 'rm').mockResolvedValue(undefined);
  const file = new File({ cwd: '/app', path: 'test.ts', lang: 'ts', content: '' });
  await file.remove();
  expect(rmSpy).toHaveBeenCalledWith(path.join('/app', 'test.ts'));
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileBuildError when the path points to a directory', async () => {
  jest.spyOn(fs, 'stat').mockResolvedValue({ isDirectory: () => true } as any);
  await expect(File.build('some-dir')).rejects.toThrow(FileBuildError);
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileBuildError when strict state is existent but file is missing', async () => {
  jest.spyOn(fs, 'stat').mockRejectedValue(new Error());
  await expect(File.build('missing.ts', { strict: true, state: 'existent' })).rejects.toThrow(FileBuildError);
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileBuildError when strict state is new but file exists', async () => {
  jest.spyOn(fs, 'stat').mockResolvedValue({ isDirectory: () => false } as any);
  await expect(File.build('exists.ts', { strict: true, state: 'new' })).rejects.toThrow(FileBuildError);
});

/* Generated by @n1k1t/unit-generator */
it('should determine the language from the file extension during build', async () => {
  jest.spyOn(fs, 'stat').mockResolvedValue({ isDirectory: () => false } as any);
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  const file = await File.build('script.js');
  expect(file.lang).toBe('js');
});

/* Generated by @n1k1t/unit-generator */
it('should join path segments when building from an array of strings', async () => {
  const statSpy = jest.spyOn(fs, 'stat').mockResolvedValue({ isDirectory: () => false } as any);
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  await File.build(['src', 'models', 'file.ts'], { cwd: '/app' });
  expect(statSpy).toHaveBeenCalledWith(path.join('/app', 'src', 'models', 'file.ts'));
});

/* Generated by @n1k1t/unit-generator */
it('should return the file instance after appending content', () => {
  const file = new File({ cwd: '.', path: 'f.ts', lang: 'ts', content: 'a' });
  expect(file.append('b')).toBe(file);
});
