import { AttachmentContent, GroupContent } from './content';
import { Project } from './project';

/* Generated by @n1k1t/unit-generator */
it('should initialize cwd from provided options in constructor', () => {
  const project = new Project({ cwd: '/test/path', sources: { skills: {}, ignore: [], files: [] } });
  expect(project.cwd).toBe('/test/path');
});

/* Generated by @n1k1t/unit-generator */
it('should use process.cwd() in constructor if cwd is not provided', () => {
  const spy = jest.spyOn(process, 'cwd').mockReturnValue('/process/cwd');
  const project = new Project({ sources: { skills: {}, ignore: [], files: [] } });
  expect(project.cwd).toBe('/process/cwd');
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should return GroupContent from content.editorconfig() when editorconfig is empty', () => {
  const project = new Project({ sources: { skills: {}, ignore: [], files: [], editorconfig: '' } });
  expect(project.content.editorconfig()).toBeInstanceOf(GroupContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return AttachmentContent from content.editorconfig() when editorconfig is present', () => {
  const project = new Project({ sources: { skills: {}, ignore: [], files: [], editorconfig: 'root = true' } });
  expect(project.content.editorconfig()).toBeInstanceOf(AttachmentContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return GroupContent from content.tree() when no files match patterns', () => {
  const project = new Project({ sources: { skills: {}, ignore: [], files: ['src/a.ts'] } });
  expect(project.content.tree(['tests/**'])).toBeInstanceOf(GroupContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return AttachmentContent from content.tree() when files match patterns', () => {
  const project = new Project({ sources: { skills: {}, ignore: [], files: ['src/a.ts'] } });
  expect(project.content.tree(['src/**'])).toBeInstanceOf(AttachmentContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return all files from files.glob() when no patterns are provided', () => {
  const files = ['a.ts', 'b.ts'];
  const project = new Project({ sources: { skills: {}, ignore: [], files } });
  expect(project.files.glob()).toEqual(files);
});

/* Generated by @n1k1t/unit-generator */
it('should filter files in files.glob() using minimatch', () => {
  const files = ['src/a.ts', 'tests/b.ts'];
  const project = new Project({ sources: { skills: {}, ignore: [], files } });
  expect(project.files.glob(['src/**'])).toEqual(['src/a.ts']);
});

/* Generated by @n1k1t/unit-generator */
it('should handle "." as "**" in files.glob() patterns', () => {
  const files = ['a.ts', 'b.ts'];
  const project = new Project({ sources: { skills: {}, ignore: [], files } });
  expect(project.files.glob(['.'])).toEqual(files);
});

/* Generated by @n1k1t/unit-generator */
it('should handle "./" prefix in files.glob() patterns', () => {
  const files = ['src/a.ts'];
  const project = new Project({ sources: { skills: {}, ignore: [], files } });
  expect(project.files.glob(['./src/**'])).toEqual(['src/a.ts']);
});

/* Generated by @n1k1t/unit-generator */
it('should add a file path using files.add()', () => {
  const project = new Project({ sources: { skills: {}, ignore: [], files: ['a.ts'] } });
  project.files.add('b.ts');
  expect(project.sources.files).toContain('b.ts');
});

/* Generated by @n1k1t/unit-generator */
it('should not add duplicate file path using files.add()', () => {
  const project = new Project({ sources: { skills: {}, ignore: [], files: ['a.ts'] } });
  project.files.add('a.ts');
  expect(project.sources.files.length).toBe(1);
});

/* Generated by @n1k1t/unit-generator */
it('should remove files starting with path using files.rm()', () => {
  const project = new Project({ sources: { skills: {}, ignore: [], files: ['src/a.ts', 'src/b.ts', 'tests/c.ts'] } });
  project.files.rm('src/');
  expect(project.sources.files).toEqual(['tests/c.ts']);
});
