import { ContentFactory } from './factory';
import { Project } from '../project';
import { File } from '../file';

import * as kinds from './kinds';

/* Generated by @n1k1t/unit-generator */
it('should create an instance of ContentFactory via the static build method', () => {
  expect(ContentFactory.build()).toBeInstanceOf(ContentFactory);
});

/* Generated by @n1k1t/unit-generator */
it('should create article content with the correct type when using title and content', () => {
  const factory = new ContentFactory();
  const article = factory.article('My Title', []);
  expect(article.type).toBe('article');
});

/* Generated by @n1k1t/unit-generator */
it('should create article content with the correct type when using a parameters object', () => {
  const factory = new ContentFactory();
  const article = factory.article({ title: 'Param Title', content: [] });
  expect(article.type).toBe('article');
});

/* Generated by @n1k1t/unit-generator */
it('should create rules content with the correct type', () => {
  const factory = new ContentFactory();
  const rules = factory.rules(['rule 1', 'rule 2']);
  expect(rules.type).toBe('rules');
});

/* Generated by @n1k1t/unit-generator */
it('should create tasks content with the correct type', () => {
  const factory = new ContentFactory();
  const tasks = factory.tasks(['task 1', 'task 2']);
  expect(tasks.type).toBe('tasks');
});

/* Generated by @n1k1t/unit-generator */
it('should create plain content with the correct type', () => {
  const factory = new ContentFactory();
  const plain = factory.plain('plain markdown text');
  expect(plain.type).toBe('plain');
});

/* Generated by @n1k1t/unit-generator */
it('should create attachment content with the correct type', () => {
  const factory = new ContentFactory();
  const attachment = factory.attachment('File Title', { content: 'file data' });
  expect(attachment.type).toBe('attachment');
});

/* Generated by @n1k1t/unit-generator */
it('should create group content for user messages with the correct type', () => {
  const factory = new ContentFactory();
  const group = factory.user('user message');
  expect(group.type).toBe('group');
});

/* Generated by @n1k1t/unit-generator */
it('should create group content for system messages with the correct type', () => {
  const factory = new ContentFactory();
  const group = factory.system('system message');
  expect(group.type).toBe('group');
});

/* Generated by @n1k1t/unit-generator */
it('should create group content from an array of strings for user messages', () => {
  const factory = new ContentFactory();
  const group = factory.user(['message 1', 'message 2']);
  expect(group.type).toBe('group');
});

/* Generated by @n1k1t/unit-generator */
it('should create group content from an existing Content instance for system messages', () => {
  const factory = new ContentFactory();
  const plain = factory.plain('text');
  const group = factory.system(plain);
  expect(group.type).toBe('group');
});

/* Generated by @n1k1t/unit-generator */
it('should return true when identifying content as the correct type using the static is method', () => {
  const factory = new ContentFactory();
  const plain = factory.plain('text');
  expect(ContentFactory.is('plain', plain)).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should return false when identifying content as the wrong type using the static is method', () => {
  const factory = new ContentFactory();
  const plain = factory.plain('text');
  expect(ContentFactory.is('article', plain)).toBe(false);
});

/* Generated by @n1k1t/unit-generator */
it('should create an ArticleContent instance when a parameters object is provided', () => {
  const factory = new ContentFactory();
  const result = factory.article({ title: 'Test Title', content: [] });
  expect(result).toBeInstanceOf(kinds.ArticleContent);
});

/* Generated by @n1k1t/unit-generator */
it('should pass the project cwd to File.build when creating a file attachment', async () => {
  const project = { cwd: '/test/path' } as Project;
  const spy = jest.spyOn(File, 'build').mockResolvedValue({ content: '', path: '' } as any);
  await new ContentFactory(project).file('Title', 'file.txt');
  expect(spy).toHaveBeenCalledWith('file.txt', { cwd: '/test/path' });
});

/* Generated by @n1k1t/unit-generator */
it('should return a ContentFactory instance from the static build method', () => {
  const factory = ContentFactory.build();
  expect(factory).toBeInstanceOf(ContentFactory);
});
